In [47]:
import pandas as pd
import os
import numpy as np

In [19]:
os.chdir("/Users/snigd/Desktop/Dropbox/UIC Data Project/Working")
cwd = os.getcwd()
cwd

'C:\\Users\\snigd\\Desktop\\Dropbox\\UIC Data Project\\Working'

In [325]:
fy18=pd.read_csv("/Users/snigd/Desktop/Dropbox/UIC Data Project/Working/fy18 eoy data chicago.csv", encoding = 'utf8')
fy19=pd.read_csv("/Users/snigd/Desktop/Dropbox/UIC Data Project/Working/Chicagofy19eoyrawdata with descriptions.csv", encoding ='utf8')

##### Creating a list of all unique schools across SY 18 and SY 19

In [326]:
schoolNamesfy18=fy18['School_FullName'].tolist()
schoolNamesfy19=fy19['School_FullName'].tolist()
print (len(list(set(schoolNamesfy18))))
print (len(list(set(schoolNamesfy19))))

39
43

In [327]:
schoolNames = set(schoolNamesfy18 + schoolNamesfy19)
#print (schoolNames)
schoolN=list(schoolNames)
#print (schoolN)
school_table=pd.DataFrame(schoolN, columns=['SchoolName'])
school_table=school_table.dropna()
school_table=school_table.sort_values(['SchoolName'])
print(len(school_table['SchoolName']))

50

##### There are 50 unique schools across SY 18 and SY 19
##### The following chunk of code will assign a school id to each school

In [328]:
school_table['school_id'] = (school_table.groupby(['SchoolName']).cumcount()==0).astype(int)
school_table['school_id'] = school_table['school_id'].cumsum()

In [329]:
school_table['initials']=np.where(school_table['school_id']<10, 'sc10','sc1')
school_table['sch_id']= school_table['initials'] + school_table.school_id.map(str)
header = ["SchoolName", "sch_id"]
school_table.to_csv('/Users/snigd/Desktop/Dropbox/UIC Data Project/Working/tables/school_table.csv', columns = header, index=False)

##### Merging the school table with SY 18 dataset provided by RIM

In [330]:
fy18.rename({'School_FullName':'SchoolName'}, axis='columns', inplace = True)

In [331]:
fy18_schid=pd.merge(fy18, school_table[['SchoolName','sch_id']], on='SchoolName',how='left', indicator=True)
fy18_schid.groupby('_merge')['SchoolName'].nunique()

_merge
left_only      0
right_only     0
both          39
Name: SchoolName, dtype: int64

##### Merging the school table with SY 19 dataset. 
##### One school name is missing in the in SY 19 dataset. Thus the school table only merges with 42 schools in SY 19

In [332]:
fy19.rename({'School_FullName':'SchoolName'}, axis='columns', inplace = True)

In [333]:
fy19_schid=pd.merge(fy19, school_table[['SchoolName','sch_id']], on='SchoolName',how='left', indicator=True)
fy19_schid.groupby('_merge')['SchoolName'].nunique()

_merge
left_only      0
right_only     0
both          42
Name: SchoolName, dtype: int64

##### Creating a list of unique teachers from SY 18 and SY 19

In [334]:
TeacherNamesfy18=fy18['Teacher'].tolist()
TeacherNamesfy19=fy19['Teacher'].tolist()
print (len(list(set(TeacherNamesfy18))))
print (len(list(set(TeacherNamesfy19))))

149
140

In [335]:
TeacherNames = set(TeacherNamesfy18 + TeacherNamesfy19)
#print (len(TeacherNames))
TeacherN=list(TeacherNames)
#print (TeacherN)
teacher_table=pd.DataFrame(TeacherN, columns=['TeacherName'])
teacher_table=teacher_table.dropna()
teacher_table=teacher_table[teacher_table.TeacherName!=',']
teacher_table=teacher_table.sort_values(['TeacherName'])
print (len(teacher_table))

209

##### There are 209 unique teacher names across SY 18 and SY 19. 
__Teacher name Washington,Cherry is present in two schools: Rachel Carson Elementary and Woodson South Elementary School. This teacher should get two unique IDs__

In [336]:
teacher_table['tch_id'] = (teacher_table.groupby(['TeacherName']).cumcount()==0).astype(int)
teacher_table['tch_id'] = teacher_table['tch_id'].cumsum()
teacher_table

              TeacherName  tch_id
20        Abdullah, Linda       1
166      Account, Preview       2
161           Acuna, Aide       3
78        Adrianzen, Anne       4
41        Alvarez, Jasmin       5
186         Amaro, Teresa       6
103      Anagnost, Yvonne       7
94      Anderson, Kristen       8
181        Barnes, Kendra       9
14         Barrera, Nadia      10
189     Barrientos, Maria      11
53         Becker, Mireya      12
22        Benitez, Teresa      13
111           Bosko, Lynn      14
162       Boyland, Maxine      15
134      Bradley, Hellena      16
198        Burian, Alicia      17
1       Butler, Florencia      18
90          Calvo, Alicia      19
34         Campana, Doris      20
205        Cardona, Cesar      21
123         Cardona, Elsa      22
125       Castillo, Maria      23
30           Cepeda, Jane      24
69            Cers, Daina      25
121         Chaian, Irena      26
149   Chambers-Jeter, Joi      27
197         Cheston, Kate      28
208             Cho, Sara      29
75      Coachman, Darlene      30
..                    ...     ...
6         Smith, Kimberly     180
136      Solis, Mary Jane     181
71      Spencer, Geogetta     182
143           Stan, Flora     183
45         Stelzel, Kayla     184
23           Story, Abena     185
146        Strunin, Sarah     186
61     Thibeau, Elizabeth     187
155         Toro, Natalie     188
28        Toy, Donnamarie     189
59          Trejo, Kristi     190
10        Turner, Ashanti     191
47      Turner, Katherine     192
113       Tzoumas, Nicole     193
165           Vega, Betsy     194
180       Veloz, Genoveva     195
101         Venzor, Diana     196
31             Wall, Mary     197
54           Walsh, Susan     198
39      Walston, Samantha     199
8      Washington, Cherry     200
16       Watson, Gretchen     201
147     Weatherred, Sarah     202
88        Whitker, Mariah     203
96       Williams, Andrea     204
77       Williams, Odessa     205
60      Williams, Valerie     206
35   Wilson-Henry, Denise     207
201          Wren, Amanda     208
27              Yang, Geo     209

[209 rows x 2 columns]

In [337]:
teacher_table['initials']=np.where(teacher_table['tch_id']<10, 'tc100','tc10')
teacher_table['initials']=np.where(teacher_table['tch_id']>=100, 'tc1',teacher_table['initials'])
teacher_table['tch_id']= teacher_table['initials'] + teacher_table.tch_id.map(str)

#teacher_table
#header = ["TeacherName", "tch_id"]
#teacher_table.to_csv('/Users/snigd/Desktop/Dropbox/UIC Data Project/Working/tables/teacher_table.csv', columns = header, index=False)

##### Merging the teacher table with SY 18 dataset

In [338]:
fy18_schid.rename({'Teacher':'TeacherName'}, axis='columns', inplace = True)

In [339]:
fy18_schid=fy18_schid.drop(['_merge'], axis=1)

In [340]:
fy18_tchid=pd.merge(fy18_schid, teacher_table[['TeacherName','tch_id']], on='TeacherName',how='left', indicator=True)
fy18_tchid.groupby('_merge')['TeacherName'].nunique()

_merge
left_only       0
right_only      0
both          149
Name: TeacherName, dtype: int64

In [341]:
fy18_tchid[['SchoolName','sch_id','tch_id', 'TeacherName']][fy18_tchid.TeacherName=='Washington, Cherry']

Empty DataFrame
Columns: [SchoolName, sch_id, tch_id, TeacherName]
Index: []

##### Merging the teacher table with SY 19 dataset

In [342]:
fy19_schid.rename({'Teacher':'TeacherName'}, axis='columns', inplace = True)

In [343]:
fy19_schid=fy19_schid.drop(['_merge'], axis=1)

In [344]:
fy19_tchid=pd.merge(fy19_schid, teacher_table[['TeacherName','tch_id']], on='TeacherName',how='left', indicator=True)
fy19_tchid.groupby('_merge')['TeacherName'].nunique()

_merge
left_only       1
right_only      0
both          139
Name: TeacherName, dtype: int64

__SY 19 dataset contained a teacher with name as ','. This did not get merged with data__

In [345]:
fy19_tchid[['SchoolName','sch_id', 'TeacherName', 'tch_id']][fy19_tchid._merge=='left_only']

                              SchoolName sch_id TeacherName tch_id
0          South Shore Fine Arts Academy  sc143           ,    NaN
1               Rachel Carson Elementary  sc140           ,    NaN
2               Dunne Technology Academy  sc109           ,    NaN
3             Metcalfe Community Academy  sc134           ,    NaN
4             Metcalfe Community Academy  sc134           ,    NaN
5   Talcott Fine Arts and Museum Academy  sc145           ,    NaN
6               Rachel Carson Elementary  sc140           ,    NaN
7            Charles W. Earle Elementary  sc104           ,    NaN
8            Charles W. Earle Elementary  sc104           ,    NaN
9            Charles W. Earle Elementary  sc104           ,    NaN
10           Charles W. Earle Elementary  sc104           ,    NaN
11           Charles W. Earle Elementary  sc104           ,    NaN
12           Charles W. Earle Elementary  sc104           ,    NaN
13           Charles W. Earle Elementary  sc104           ,    NaN
14           Charles W. Earle Elementary  sc104           ,    NaN
15           Charles W. Earle Elementary  sc104           ,    NaN
16           Charles W. Earle Elementary  sc104           ,    NaN
17           Charles W. Earle Elementary  sc104           ,    NaN
18           Charles W. Earle Elementary  sc104           ,    NaN
19           Charles W. Earle Elementary  sc104           ,    NaN
20           Charles W. Earle Elementary  sc104           ,    NaN
21           Charles W. Earle Elementary  sc104           ,    NaN
22           Charles W. Earle Elementary  sc104           ,    NaN
23           Charles W. Earle Elementary  sc104           ,    NaN
24           Charles W. Earle Elementary  sc104           ,    NaN
25           Charles W. Earle Elementary  sc104           ,    NaN
26           Charles W. Earle Elementary  sc104           ,    NaN
27           Charles W. Earle Elementary  sc104           ,    NaN
28           Charles W. Earle Elementary  sc104           ,    NaN
29           Charles W. Earle Elementary  sc104           ,    NaN
30           Charles W. Earle Elementary  sc104           ,    NaN
31           Charles W. Earle Elementary  sc104           ,    NaN
32           Charles W. Earle Elementary  sc104           ,    NaN
33           Charles W. Earle Elementary  sc104           ,    NaN
34           Charles W. Earle Elementary  sc104           ,    NaN
35           Charles W. Earle Elementary  sc104           ,    NaN
36           Charles W. Earle Elementary  sc104           ,    NaN
37           Charles W. Earle Elementary  sc104           ,    NaN
38           Charles W. Earle Elementary  sc104           ,    NaN
39           Charles W. Earle Elementary  sc104           ,    NaN
40           Charles W. Earle Elementary  sc104           ,    NaN
41           Charles W. Earle Elementary  sc104           ,    NaN
42           Charles W. Earle Elementary  sc104           ,    NaN
43           Charles W. Earle Elementary  sc104           ,    NaN
44           Charles W. Earle Elementary  sc104           ,    NaN
45           Charles W. Earle Elementary  sc104           ,    NaN
46           Charles W. Earle Elementary  sc104           ,    NaN
47           Charles W. Earle Elementary  sc104           ,    NaN
48           Charles W. Earle Elementary  sc104           ,    NaN
49           Charles W. Earle Elementary  sc104           ,    NaN
50           Charles W. Earle Elementary  sc104           ,    NaN
51           Charles W. Earle Elementary  sc104           ,    NaN
52           Charles W. Earle Elementary  sc104           ,    NaN
53           Charles W. Earle Elementary  sc104           ,    NaN
54           Charles W. Earle Elementary  sc104           ,    NaN
55           Charles W. Earle Elementary  sc104           ,    NaN
56           Charles W. Earle Elementary  sc104           ,    NaN
57           Charles W. Earle Elementary  sc104           ,    NaN
58           Charles W. Earle Elementary  sc104           ,    NaN

__Washington, Cherry has only one record for Rachel Carson Elementary School. All other student data points for this school teacher combination is missing suggesting a data entry error. Removing this record of Washington, Cherry.__

In [346]:
fy19_tchid[['SchoolName','sch_id','tch_id', 'TeacherName']][fy19_tchid.TeacherName=='Washington, Cherry']

                           SchoolName sch_id  tch_id         TeacherName
7064         Rachel Carson Elementary  sc140  tc1200  Washington, Cherry
7065  Woodson South Elementary School  sc150  tc1200  Washington, Cherry
7066  Woodson South Elementary School  sc150  tc1200  Washington, Cherry
7067  Woodson South Elementary School  sc150  tc1200  Washington, Cherry
7068  Woodson South Elementary School  sc150  tc1200  Washington, Cherry
7069  Woodson South Elementary School  sc150  tc1200  Washington, Cherry
7070  Woodson South Elementary School  sc150  tc1200  Washington, Cherry
7071  Woodson South Elementary School  sc150  tc1200  Washington, Cherry
7072  Woodson South Elementary School  sc150  tc1200  Washington, Cherry
7073  Woodson South Elementary School  sc150  tc1200  Washington, Cherry
7074  Woodson South Elementary School  sc150  tc1200  Washington, Cherry
7075  Woodson South Elementary School  sc150  tc1200  Washington, Cherry
7076  Woodson South Elementary School  sc150  tc1200  Washington, Cherry
7077  Woodson South Elementary School  sc150  tc1200  Washington, Cherry
7078  Woodson South Elementary School  sc150  tc1200  Washington, Cherry
7079  Woodson South Elementary School  sc150  tc1200  Washington, Cherry
7080  Woodson South Elementary School  sc150  tc1200  Washington, Cherry
7081  Woodson South Elementary School  sc150  tc1200  Washington, Cherry
7082  Woodson South Elementary School  sc150  tc1200  Washington, Cherry
7083  Woodson South Elementary School  sc150  tc1200  Washington, Cherry
7084  Woodson South Elementary School  sc150  tc1200  Washington, Cherry
7085  Woodson South Elementary School  sc150  tc1200  Washington, Cherry
7086  Woodson South Elementary School  sc150  tc1200  Washington, Cherry
7087  Woodson South Elementary School  sc150  tc1200  Washington, Cherry
7088  Woodson South Elementary School  sc150  tc1200  Washington, Cherry
7089  Woodson South Elementary School  sc150  tc1200  Washington, Cherry
7090  Woodson South Elementary School  sc150  tc1200  Washington, Cherry
7091  Woodson South Elementary School  sc150  tc1200  Washington, Cherry
7092  Woodson South Elementary School  sc150  tc1200  Washington, Cherry
7093  Woodson South Elementary School  sc150  tc1200  Washington, Cherry
...                               ...    ...     ...                 ...
7171  Woodson South Elementary School  sc150  tc1200  Washington, Cherry
7172  Woodson South Elementary School  sc150  tc1200  Washington, Cherry
7173  Woodson South Elementary School  sc150  tc1200  Washington, Cherry
7174  Woodson South Elementary School  sc150  tc1200  Washington, Cherry
7175  Woodson South Elementary School  sc150  tc1200  Washington, Cherry
7176  Woodson South Elementary School  sc150  tc1200  Washington, Cherry
7177  Woodson South Elementary School  sc150  tc1200  Washington, Cherry
7178  Woodson South Elementary School  sc150  tc1200  Washington, Cherry
7179  Woodson South Elementary School  sc150  tc1200  Washington, Cherry
7180  Woodson South Elementary School  sc150  tc1200  Washington, Cherry
7181  Woodson South Elementary School  sc150  tc1200  Washington, Cherry
7182  Woodson South Elementary School  sc150  tc1200  Washington, Cherry
7183  Woodson South Elementary School  sc150  tc1200  Washington, Cherry
7184  Woodson South Elementary School  sc150  tc1200  Washington, Cherry
7185  Woodson South Elementary School  sc150  tc1200  Washington, Cherry
7186  Woodson South Elementary School  sc150  tc1200  Washington, Cherry
7187  Woodson South Elementary School  sc150  tc1200  Washington, Cherry
7188  Woodson South Elementary School  sc150  tc1200  Washington, Cherry
7189  Woodson South Elementary School  sc150  tc1200  Washington, Cherry
7190  Woodson South Elementary School  sc150  tc1200  Washington, Cherry
7191  Woodson South Elementary School  sc150  tc1200  Washington, Cherry
7192  Woodson South Elementary School  sc150  tc1200  Washington, Cherry
7193  Woodson South Elementary School  sc150  tc1200  Washington, Cherry
7194  Woodson South Elementary School  sc150  tc1200  Washington, Cherry
7195  Woodson South Elementary School  sc150  tc1200  Washington, Cherry
7196  Woodson South Elementary School  sc150  tc1200  Washington, Cherry
7197  Woodson South Elementary School  sc150  tc1200  Washington, Cherry
7198  Woodson South Elementary School  sc150  tc1200  Washington, Cherry
7199  Woodson South Elementary School  sc150  tc1200  Washington, Cherry
7200  Woodson South Elementary School  sc150  tc1200  Washington, Cherry

[137 rows x 4 columns]

In [347]:
fy19_tchid=fy19_tchid[~((fy19_tchid['tch_id']=='tc1200') & (fy19_tchid['sch_id']=='sc140'))]

In [348]:
fy19_tchid=fy19_tchid[fy19_tchid['TeacherName'] !=',']

In [349]:
fy18_tchid=fy18_tchid.drop(['_merge'], axis=1)
fy19_tchid=fy19_tchid.drop(['_merge'], axis=1)

##### Merging SY 18 and SY 19 and keeping only teacher and school variables to arrive at a complete teacher table

In [350]:
fy18_19=pd.merge(fy18_tchid[['SchoolName','sch_id','TeacherName','tch_id']],fy19_tchid[['SchoolName','sch_id','TeacherName','tch_id']]
                , on = ['sch_id','tch_id'], how='outer', indicator=True)

In [351]:
fy18_19

,SchoolName_x,sch_id,TeacherName_x,tch_id,SchoolName_y,TeacherName_y,_merge
0,Shoesmith,sc141,"Hobson, Ashley",tc1074,NaN,NaN,left_only
1,Shoesmith,sc141,"Hobson, Ashley",tc1074,NaN,NaN,left_only
2,Shoesmith,sc141,"Hobson, Ashley",tc1074,NaN,NaN,left_only
3,Shoesmith,sc141,"Hobson, Ashley",tc1074,NaN,NaN,left_only
4,Shoesmith,sc141,"Hobson, Ashley",tc1074,NaN,NaN,left_only
5,Shoesmith,sc141,"Hobson, Ashley",tc1074,NaN,NaN,left_only
6,Shoesmith,sc141,"Hobson, Ashley",tc1074,NaN,NaN,left_only
7,Shoesmith,sc141,"Hobson, Ashley",tc1074,NaN,NaN,left_only
8,Shoesmith,sc141,"Hobson, Ashley",tc1074,NaN,NaN,left_only
9,Shoesmith,sc141,"Hobson, Ashley",tc1074,NaN,NaN,left_only
10,Shoesmith,sc141,"Hobson, Ashley",tc1074,NaN,NaN,left_only
11,Shoesmith,sc141,"Hobson, Ashley",tc1074,NaN,NaN,left_only
12,Shoesmith,sc141,"Hobson, Ashley",tc1074,NaN,NaN,left_only
13,Shoesmith,sc141,"Hobson, Ashley",tc1074,NaN,NaN,left_only
14,Shoesmith,sc141,"Hobson, Ashley",tc1074,NaN,NaN,left_only
15,Shoesmith,sc141,"Hobson, Ashley",tc1074,NaN,NaN,left_only
16,Shoesmith,sc141,"Hobson, Ashley",tc1074,NaN,NaN,left_only
17,Shoesmith,sc141,"Hobson, Ashley",tc1074,NaN,NaN,left_only
18,Shoesmith,sc141,"Hobson, Ashley",tc1074,NaN,NaN,left_only
19,Shoesmith,sc141,"Hobson, Ashley",tc1074,NaN,NaN,left_only
20,Shoesmith,sc141,"Hobson, Ashley",tc1074,NaN,NaN,left_only
21,Shoesmith,sc141,"Hobson, Ashley",tc1074,NaN,NaN,left_only
22,Shoesmith,sc141,"Hobson, Ashley",tc1074,NaN,NaN,left_only
23,Shoesmith,sc141,"Hobson, Ashley",tc1074,NaN,NaN,left_only
24,Shoesmith,sc141,"Hobson, Ashley",tc1074,NaN,NaN,left_only
25,Shoesmith,sc141,"Hobson, Ashley",tc1074,NaN,NaN,left_only
26,Shoesmith,sc141,"Hobson, Ashley",tc1074,NaN,NaN,left_only
27,Shoesmith,sc141,"Hobson, Ashley",tc1074,NaN,NaN,left_only
28,Shoesmith,sc141,"Hobson, Ashley",tc1074,NaN,NaN,left_only
29,Shoesmith,sc141,"Hobson, Ashley",tc1074,NaN,NaN,left_only
...,...,...,...,...,...,...,...
563108,NaN,sc108,NaN,tc1205,Dr. Marting L. King Jr. Academy of Social Justice,"Williams, Odessa",right_only
563109,NaN,sc108,NaN,tc1205,Dr. Marting L. King Jr. Academy of Social Justice,"Williams, Odessa",right_only
563110,NaN,sc108,NaN,tc1205,Dr. Marting L. King Jr. Academy of Social Justice,"Williams, Odessa",right_only
563111,NaN,sc108,NaN,tc1205,Dr. Marting L. King Jr. Academy of Social Justice,"Williams, Odessa",right_only
563112,NaN,sc108,NaN,tc1205,Dr. Marting L. King Jr. Academy of Social Justice,"Williams, Odessa",right_only
563113,NaN,sc108,NaN,tc1205,Dr. Marting L. King Jr. Academy of Social Justice,"Williams, Odessa",right_only
563114,NaN,sc108,NaN,tc1205,Dr. Marting L. King Jr. Academy of Social Justice,"Williams, Odessa",right_only
563115,NaN,sc108,NaN,tc1205,Dr. Marting L. King Jr. Academy of Social Justice,"Williams, Odessa",right_only
563116,NaN,sc108,NaN,tc1205,Dr. Marting L. King Jr. Academy of Social Justice,"Williams, Odessa",right_only
563117,NaN,sc108,NaN,tc1205,Dr. Marting L. King Jr. Academy of Social Justice,"Williams, Odessa",right_only
563118,NaN,sc108,NaN,tc1205,Dr. Marting L. King Jr. Academy of Social Justice,"Williams, Odessa",right_only
563119,NaN,sc108,NaN,tc1205,Dr. Marting L. King Jr. Academy of Social Justice,"Williams, Odessa",right_only
563120,NaN,sc108,NaN,tc1205,Dr. Marting L. King Jr. Academy of Social Justice,"Williams, Odessa",right_only
563121,NaN,sc108,NaN,tc1205,Dr. Marting L. King Jr. Academy of Social Justice,"Williams, Odessa",right_only
563122,NaN,sc108,NaN,tc1205,Dr. Marting L. King Jr. Academy of Social Justice,"Williams, Odessa",right_only
563123,NaN,sc108,NaN,tc1205,Dr. Marting L. King Jr. Academy of Social Justice,"Williams, Odessa",right_only
563124,NaN,sc108,NaN,tc1205,Dr. Marting L. King Jr. Academy of Social Justice,"Williams, Odessa",right_only
563125,NaN,sc108,NaN,tc1205,Dr. Marting L. King Jr. Academy of Social Justice,"Williams, Odessa",right_only
563126,NaN,sc108,NaN,tc1205,Dr. Marting L. King Jr. Academy of Social Justice,"Williams, Odessa",right_only
563127,NaN,sc108,NaN,tc1205,Dr. Marting L. King Jr. Academy of Social Justice,"Williams, Odessa",right_only
563128,NaN,sc108,NaN,tc1205,Dr. Marting L. King Jr. Academy of Social Justice,"Williams, Odessa",right_only
563129,NaN,sc108,NaN,tc1205,Dr. Marting L. King Jr. Academy of Social Justice,"Williams, Odessa",right_only
563130,NaN,sc108,NaN,tc1205,Dr. Marting L. King Jr. Academy of Social Justice,"Williams, Odessa",right_only
563131,NaN,sc108,NaN,tc1205,Dr. Marting L. King Jr. Academy of Social Justice,"Williams, Odessa",right_only
563132,NaN,sc108,NaN,tc1205,Dr. Marting L. King Jr. Academy of Social Justice,"Williams, Odessa",right_only
563133,NaN,sc108,NaN,tc1205,Dr. Marting L. King Jr. Academy of Social Justice,"Williams, Odessa",right_only
563134,NaN,sc108,NaN,tc1205,Dr. Marting L. King Jr. Academy of Social Justice,"Williams, Odessa",right_only
563135,NaN,sc108,NaN,tc1205,Dr. Marting L. King Jr. Academy of Social Justice,"Williams, Odessa",right_only
563136,NaN,sc108,NaN,tc1205,Dr. Marting L. King Jr. Academy of Social Justice,"Williams, Odessa",right_only
563137,NaN,sc108,NaN,tc1205,Dr. Marting L. King Jr. Academy of Social Justice,"Williams, Odessa",right_only

In [352]:
fy18_19.groupby('_merge')['sch_id'].nunique()

_merge
left_only     29
right_only    33
both          31
Name: sch_id, dtype: int64

##### Creating one unique column for all teacher names and school names

In [353]:
fy18_19['SchoolName']=fy18_19['SchoolName_x']
fy18_19['SchoolName']=np.where(fy18_19['_merge']=='right_only', fy18_19['SchoolName_y'], fy18_19['SchoolName'])
fy18_19['TeacherName']=fy18_19['TeacherName_x']
fy18_19['TeacherName']=np.where(fy18_19['_merge']=='right_only', fy18_19['TeacherName_y'], fy18_19['TeacherName'])
fy18_19

,SchoolName_x,sch_id,TeacherName_x,tch_id,SchoolName_y,TeacherName_y,_merge,SchoolName,TeacherName
0,Shoesmith,sc141,"Hobson, Ashley",tc1074,NaN,NaN,left_only,Shoesmith,"Hobson, Ashley"
1,Shoesmith,sc141,"Hobson, Ashley",tc1074,NaN,NaN,left_only,Shoesmith,"Hobson, Ashley"
2,Shoesmith,sc141,"Hobson, Ashley",tc1074,NaN,NaN,left_only,Shoesmith,"Hobson, Ashley"
3,Shoesmith,sc141,"Hobson, Ashley",tc1074,NaN,NaN,left_only,Shoesmith,"Hobson, Ashley"
4,Shoesmith,sc141,"Hobson, Ashley",tc1074,NaN,NaN,left_only,Shoesmith,"Hobson, Ashley"
5,Shoesmith,sc141,"Hobson, Ashley",tc1074,NaN,NaN,left_only,Shoesmith,"Hobson, Ashley"
6,Shoesmith,sc141,"Hobson, Ashley",tc1074,NaN,NaN,left_only,Shoesmith,"Hobson, Ashley"
7,Shoesmith,sc141,"Hobson, Ashley",tc1074,NaN,NaN,left_only,Shoesmith,"Hobson, Ashley"
8,Shoesmith,sc141,"Hobson, Ashley",tc1074,NaN,NaN,left_only,Shoesmith,"Hobson, Ashley"
9,Shoesmith,sc141,"Hobson, Ashley",tc1074,NaN,NaN,left_only,Shoesmith,"Hobson, Ashley"
10,Shoesmith,sc141,"Hobson, Ashley",tc1074,NaN,NaN,left_only,Shoesmith,"Hobson, Ashley"
11,Shoesmith,sc141,"Hobson, Ashley",tc1074,NaN,NaN,left_only,Shoesmith,"Hobson, Ashley"
12,Shoesmith,sc141,"Hobson, Ashley",tc1074,NaN,NaN,left_only,Shoesmith,"Hobson, Ashley"
13,Shoesmith,sc141,"Hobson, Ashley",tc1074,NaN,NaN,left_only,Shoesmith,"Hobson, Ashley"
14,Shoesmith,sc141,"Hobson, Ashley",tc1074,NaN,NaN,left_only,Shoesmith,"Hobson, Ashley"
15,Shoesmith,sc141,"Hobson, Ashley",tc1074,NaN,NaN,left_only,Shoesmith,"Hobson, Ashley"
16,Shoesmith,sc141,"Hobson, Ashley",tc1074,NaN,NaN,left_only,Shoesmith,"Hobson, Ashley"
17,Shoesmith,sc141,"Hobson, Ashley",tc1074,NaN,NaN,left_only,Shoesmith,"Hobson, Ashley"
18,Shoesmith,sc141,"Hobson, Ashley",tc1074,NaN,NaN,left_only,Shoesmith,"Hobson, Ashley"
19,Shoesmith,sc141,"Hobson, Ashley",tc1074,NaN,NaN,left_only,Shoesmith,"Hobson, Ashley"
20,Shoesmith,sc141,"Hobson, Ashley",tc1074,NaN,NaN,left_only,Shoesmith,"Hobson, Ashley"
21,Shoesmith,sc141,"Hobson, Ashley",tc1074,NaN,NaN,left_only,Shoesmith,"Hobson, Ashley"
22,Shoesmith,sc141,"Hobson, Ashley",tc1074,NaN,NaN,left_only,Shoesmith,"Hobson, Ashley"
23,Shoesmith,sc141,"Hobson, Ashley",tc1074,NaN,NaN,left_only,Shoesmith,"Hobson, Ashley"
24,Shoesmith,sc141,"Hobson, Ashley",tc1074,NaN,NaN,left_only,Shoesmith,"Hobson, Ashley"
25,Shoesmith,sc141,"Hobson, Ashley",tc1074,NaN,NaN,left_only,Shoesmith,"Hobson, Ashley"
26,Shoesmith,sc141,"Hobson, Ashley",tc1074,NaN,NaN,left_only,Shoesmith,"Hobson, Ashley"
27,Shoesmith,sc141,"Hobson, Ashley",tc1074,NaN,NaN,left_only,Shoesmith,"Hobson, Ashley"
28,Shoesmith,sc141,"Hobson, Ashley",tc1074,NaN,NaN,left_only,Shoesmith,"Hobson, Ashley"
29,Shoesmith,sc141,"Hobson, Ashley",tc1074,NaN,NaN,left_only,Shoesmith,"Hobson, Ashley"
...,...,...,...,...,...,...,...,...,...
563108,NaN,sc108,NaN,tc1205,Dr. Marting L. King Jr. Academy of Social Justice,"Williams, Odessa",right_only,Dr. Marting L. King Jr. Academy of Social Justice,"Williams, Odessa"
563109,NaN,sc108,NaN,tc1205,Dr. Marting L. King Jr. Academy of Social Justice,"Williams, Odessa",right_only,Dr. Marting L. King Jr. Academy of Social Justice,"Williams, Odessa"
563110,NaN,sc108,NaN,tc1205,Dr. Marting L. King Jr. Academy of Social Justice,"Williams, Odessa",right_only,Dr. Marting L. King Jr. Academy of Social Justice,"Williams, Odessa"
563111,NaN,sc108,NaN,tc1205,Dr. Marting L. King Jr. Academy of Social Justice,"Williams, Odessa",right_only,Dr. Marting L. King Jr. Academy of Social Justice,"Williams, Odessa"
563112,NaN,sc108,NaN,tc1205,Dr. Marting L. King Jr. Academy of Social Justice,"Williams, Odessa",right_only,Dr. Marting L. King Jr. Academy of Social Justice,"Williams, Odessa"
563113,NaN,sc108,NaN,tc1205,Dr. Marting L. King Jr. Academy of Social Justice,"Williams, Odessa",right_only,Dr. Marting L. King Jr. Academy of Social Justice,"Williams, Odessa"
563114,NaN,sc108,NaN,tc1205,Dr. Marting L. King Jr. Academy of Social Justice,"Williams, Odessa",right_only,Dr. Marting L. King Jr. Academy of Social Justice,"Williams, Odessa"
563115,NaN,sc108,NaN,tc1205,Dr. Marting L. King Jr. Academy of Social Justice,"Williams, Odessa",right_only,Dr. Marting L. King Jr. Academy of Social Justice,"Williams, Odessa"
563116,NaN,sc108,NaN,tc1205,Dr. Marting L. King Jr. Academy of Social Justice,"Williams, Odessa",right_only,Dr. Marting L. King Jr. Academy of Social Justice,"Williams, Odessa"
563117,NaN,sc108,NaN,tc1205,Dr. Marting L. King Jr. Academy of Social Justice,"Williams, Odessa",right_only,Dr. Marting L. King Jr. Academy of Social Justice,"Williams, Odessa"
563118,NaN,sc108,NaN,tc1205,Dr. Marting L. King Jr. Academy of Social Justice,"Williams, Odessa",right_only,Dr. Marting L. King Jr. Academy of Social Justice,"Williams, Odessa"
563119,NaN,sc108,NaN,tc1205,Dr. Marting L. King Jr. Academy of Social Justice,"Williams, Odessa",right_only,Dr. Marting L. King Jr. Academy of Social Justice,"Williams, Odessa"
563120,NaN,sc108,NaN,tc1205,Dr. Marting L. King Jr. Academy of Social Justice,"Williams, Odessa",right_only,Dr. Marting L. King Jr. Academy of Social Justice,"Williams, Odessa"
563121,NaN,sc108,NaN,tc1205,Dr. Marting L. King Jr. Academy of Social Justice,"Williams, Odessa",right_only,Dr. Marting L. King Jr. Academy of Social Justice,"Williams, Odessa"
563122,NaN,sc108,NaN,tc1205,Dr. Marting L. King Jr. Academy of Social Justice,"Williams, Odessa",right_only,Dr. Marting L. King Jr. Academy of Social Justice,"Williams, Odessa"
563123,NaN,sc108,NaN,tc1205,Dr. Marting L. King Jr. Academy of Social Justice,"Williams, Odessa",right_only,Dr. Marting L. King Jr. Academy of Social Justice,"Williams, Odessa"
563124,NaN,sc108,NaN,tc1205,Dr. Marting L. King Jr. Academy of Social Justice,"Williams, Odessa",right_only,Dr. Marting L. King Jr. Academy of Social Justice,"Williams, Odessa"
563125,NaN,sc108,NaN,tc1205,Dr. Marting L. King Jr. Academy of Social Justice,"Williams, Odessa",right_only,Dr. Marting L. King Jr. Academy of Social Justice,"Williams, Odessa"
563126,NaN,sc108,NaN,tc1205,Dr. Marting L. King Jr. Academy of Social Justice,"Williams, Odessa",right_only,Dr. Marting L. King Jr. Academy of Social Justice,"Williams, Odessa"
563127,NaN,sc108,NaN,tc1205,Dr. Marting L. King Jr. Academy of Social Justice,"Williams, Odessa",right_only,Dr. Marting L. King Jr. Academy of Social Justice,"Williams, Odessa"
563128,NaN,sc108,NaN,tc1205,Dr. Marting L. King Jr. Academy of Social Justice,"Williams, Odessa",right_only,Dr. Marting L. King Jr. Academy of Social Justice,"Williams, Odessa"
563129,NaN,sc108,NaN,tc1205,Dr. Marting L. King Jr. Academy of Social Justice,"Williams, Odessa",right_only,Dr. Marting L. King Jr. Academy of Social Justice,"Williams, Odessa"
563130,NaN,sc108,NaN,tc1205,Dr. Marting L. King Jr. Academy of Social Justice,"Williams, Odessa",right_only,Dr. Marting L. King Jr. Academy of Social Justice,"Williams, Odessa"
563131,NaN,sc108,NaN,tc1205,Dr. Marting L. King Jr. Academy of Social Justice,"Williams, Odessa",right_only,Dr. Marting L. King Jr. Academy of Social Justice,"Williams, Odessa"
563132,NaN,sc108,NaN,tc1205,Dr. Marting L. King Jr. Academy of Social Justice,"Williams, Odessa",right_only,Dr. Marting L. King Jr. Academy of Social Justice,"Williams, Odessa"
563133,NaN,sc108,NaN,tc1205,Dr. Marting L. King Jr. Academy of Social Justice,"Williams, Odessa",right_only,Dr. Marting L. King Jr. Academy of Social Justice,"Williams, Odessa"
563134,NaN,sc108,NaN,tc1205,Dr. Marting L. King Jr. Academy of Social Justice,"Williams, Odessa",right_only,Dr. Marting L. King Jr. Academy of Social Justice,"Williams, Odessa"
563135,NaN,sc108,NaN,tc1205,Dr. Marting L. King Jr. Academy of Social Justice,"Williams, Odessa",right_only,Dr. Marting L. King Jr. Academy of Social Justice,"Williams, Odessa"
563136,NaN,sc108,NaN,tc1205,Dr. Marting L. King Jr. Academy of Social Justice,"Williams, Odessa",right_only,Dr. Marting L. King Jr. Academy of Social Justice,"Williams, Odessa"
563137,NaN,sc108,NaN,tc1205,Dr. Marting L. King Jr. Academy of Social Justice,"Williams, Odessa",right_only,Dr. Marting L. King Jr. Academy of Social Justice,"Williams, Odessa"

In [354]:
fy18_19=fy18_19.drop(['SchoolName_x','SchoolName_y','TeacherName_x','TeacherName_y'], axis=1)
fy18_19

,sch_id,tch_id,_merge,SchoolName,TeacherName
0,sc141,tc1074,left_only,Shoesmith,"Hobson, Ashley"
1,sc141,tc1074,left_only,Shoesmith,"Hobson, Ashley"
2,sc141,tc1074,left_only,Shoesmith,"Hobson, Ashley"
3,sc141,tc1074,left_only,Shoesmith,"Hobson, Ashley"
4,sc141,tc1074,left_only,Shoesmith,"Hobson, Ashley"
5,sc141,tc1074,left_only,Shoesmith,"Hobson, Ashley"
6,sc141,tc1074,left_only,Shoesmith,"Hobson, Ashley"
7,sc141,tc1074,left_only,Shoesmith,"Hobson, Ashley"
8,sc141,tc1074,left_only,Shoesmith,"Hobson, Ashley"
9,sc141,tc1074,left_only,Shoesmith,"Hobson, Ashley"
10,sc141,tc1074,left_only,Shoesmith,"Hobson, Ashley"
11,sc141,tc1074,left_only,Shoesmith,"Hobson, Ashley"
12,sc141,tc1074,left_only,Shoesmith,"Hobson, Ashley"
13,sc141,tc1074,left_only,Shoesmith,"Hobson, Ashley"
14,sc141,tc1074,left_only,Shoesmith,"Hobson, Ashley"
15,sc141,tc1074,left_only,Shoesmith,"Hobson, Ashley"
16,sc141,tc1074,left_only,Shoesmith,"Hobson, Ashley"
17,sc141,tc1074,left_only,Shoesmith,"Hobson, Ashley"
18,sc141,tc1074,left_only,Shoesmith,"Hobson, Ashley"
19,sc141,tc1074,left_only,Shoesmith,"Hobson, Ashley"
20,sc141,tc1074,left_only,Shoesmith,"Hobson, Ashley"
21,sc141,tc1074,left_only,Shoesmith,"Hobson, Ashley"
22,sc141,tc1074,left_only,Shoesmith,"Hobson, Ashley"
23,sc141,tc1074,left_only,Shoesmith,"Hobson, Ashley"
24,sc141,tc1074,left_only,Shoesmith,"Hobson, Ashley"
25,sc141,tc1074,left_only,Shoesmith,"Hobson, Ashley"
26,sc141,tc1074,left_only,Shoesmith,"Hobson, Ashley"
27,sc141,tc1074,left_only,Shoesmith,"Hobson, Ashley"
28,sc141,tc1074,left_only,Shoesmith,"Hobson, Ashley"
29,sc141,tc1074,left_only,Shoesmith,"Hobson, Ashley"
...,...,...,...,...,...
563108,sc108,tc1205,right_only,Dr. Marting L. King Jr. Academy of Social Justice,"Williams, Odessa"
563109,sc108,tc1205,right_only,Dr. Marting L. King Jr. Academy of Social Justice,"Williams, Odessa"
563110,sc108,tc1205,right_only,Dr. Marting L. King Jr. Academy of Social Justice,"Williams, Odessa"
563111,sc108,tc1205,right_only,Dr. Marting L. King Jr. Academy of Social Justice,"Williams, Odessa"
563112,sc108,tc1205,right_only,Dr. Marting L. King Jr. Academy of Social Justice,"Williams, Odessa"
563113,sc108,tc1205,right_only,Dr. Marting L. King Jr. Academy of Social Justice,"Williams, Odessa"
563114,sc108,tc1205,right_only,Dr. Marting L. King Jr. Academy of Social Justice,"Williams, Odessa"
563115,sc108,tc1205,right_only,Dr. Marting L. King Jr. Academy of Social Justice,"Williams, Odessa"
563116,sc108,tc1205,right_only,Dr. Marting L. King Jr. Academy of Social Justice,"Williams, Odessa"
563117,sc108,tc1205,right_only,Dr. Marting L. King Jr. Academy of Social Justice,"Williams, Odessa"
563118,sc108,tc1205,right_only,Dr. Marting L. King Jr. Academy of Social Justice,"Williams, Odessa"
563119,sc108,tc1205,right_only,Dr. Marting L. King Jr. Academy of Social Justice,"Williams, Odessa"
563120,sc108,tc1205,right_only,Dr. Marting L. King Jr. Academy of Social Justice,"Williams, Odessa"
563121,sc108,tc1205,right_only,Dr. Marting L. King Jr. Academy of Social Justice,"Williams, Odessa"
563122,sc108,tc1205,right_only,Dr. Marting L. King Jr. Academy of Social Justice,"Williams, Odessa"
563123,sc108,tc1205,right_only,Dr. Marting L. King Jr. Academy of Social Justice,"Williams, Odessa"
563124,sc108,tc1205,right_only,Dr. Marting L. King Jr. Academy of Social Justice,"Williams, Odessa"
563125,sc108,tc1205,right_only,Dr. Marting L. King Jr. Academy of Social Justice,"Williams, Odessa"
563126,sc108,tc1205,right_only,Dr. Marting L. King Jr. Academy of Social Justice,"Williams, Odessa"
563127,sc108,tc1205,right_only,Dr. Marting L. King Jr. Academy of Social Justice,"Williams, Odessa"
563128,sc108,tc1205,right_only,Dr. Marting L. King Jr. Academy of Social Justice,"Williams, Odessa"
563129,sc108,tc1205,right_only,Dr. Marting L. King Jr. Academy of Social Justice,"Williams, Odessa"
563130,sc108,tc1205,right_only,Dr. Marting L. King Jr. Academy of Social Justice,"Williams, Odessa"
563131,sc108,tc1205,right_only,Dr. Marting L. King Jr. Academy of Social Justice,"Williams, Odessa"
563132,sc108,tc1205,right_only,Dr. Marting L. King Jr. Academy of Social Justice,"Williams, Odessa"
563133,sc108,tc1205,right_only,Dr. Marting L. King Jr. Academy of Social Justice,"Williams, Odessa"
563134,sc108,tc1205,right_only,Dr. Marting L. King Jr. Academy of Social Justice,"Williams, Odessa"
563135,sc108,tc1205,right_only,Dr. Marting L. King Jr. Academy of Social Justice,"Williams, Odessa"
563136,sc108,tc1205,right_only,Dr. Marting L. King Jr. Academy of Social Justice,"Williams, Odessa"
563137,sc108,tc1205,right_only,Dr. Marting L. King Jr. Academy of Social Justice,"Williams, Odessa"

In [355]:
fy18_19.drop_duplicates(subset=['sch_id','tch_id'],keep='first', inplace=True)
fy18_19.sort_values(['sch_id','tch_id'])

,sch_id,tch_id,_merge,SchoolName,TeacherName
165891,sc101,tc1022,both,Alfred Nobel Elementary School,"Cardona, Elsa"
181150,sc101,tc1034,both,Alfred Nobel Elementary School,"Contreras, Jasmine"
119014,sc101,tc1091,both,Alfred Nobel Elementary School,"Kolasa, Susi"
158871,sc101,tc1111,both,Alfred Nobel Elementary School,"McCarter, Lisa"
152807,sc101,tc1160,left_only,Alfred Nobel Elementary School,"Romano, Nikki"
560118,sc101,tc1165,right_only,Alfred Nobel Elementary School,"Salgado, Yaneli"
393586,sc101,tc1193,left_only,Alfred Nobel Elementary School,"Tzoumas, Nicole"
560315,sc101,tc1197,right_only,Alfred Nobel Elementary School,"Wall, Mary"
407287,sc102,tc1068,both,Bret Harte Elementary,"Grib, Megan"
422662,sc102,tc1118,both,Bret Harte Elementary,"Mitchell, Faith"
447026,sc103,tc1015,left_only,Carver Primary School,"Boyland, Maxine"
447135,sc103,tc1192,left_only,Carver Primary School,"Turner, Katherine"
522568,sc104,tc1059,both,Charles W. Earle Elementary,"Funches, Shatara"
528396,sc104,tc1072,left_only,Charles W. Earle Elementary,"Henderson, Teresa"
560551,sc104,tc1080,right_only,Charles W. Earle Elementary,"Jiang, Diana"
528469,sc104,tc1137,left_only,Charles W. Earle Elementary,"Power, Gabrielle"
102067,sc104,tc1178,left_only,Charles W. Earle Elementary,"Sims, Tonya"
173844,sc105,tc1065,both,Cleveland,"Gomez, Priscilla"
13756,sc105,tc1151,both,Cleveland,"Rivera, Maricela"
25184,sc105,tc1201,both,Cleveland,"Watson, Gretchen"
144,sc105,tc1208,both,Cleveland,"Wren, Amanda"
74731,sc106,tc1010,both,Columbia Explorers Elementary Academy,"Barrera, Nadia"
189331,sc106,tc1012,both,Columbia Explorers Elementary Academy,"Becker, Mireya"
85332,sc106,tc1024,both,Columbia Explorers Elementary Academy,"Cepeda, Jane"
560038,sc106,tc1029,right_only,Columbia Explorers Elementary Academy,"Cho, Sara"
101913,sc106,tc1039,left_only,Columbia Explorers Elementary Academy,"Cueva, Daniela"
324774,sc106,tc1053,left_only,Columbia Explorers Elementary Academy,"Fair, Megan"
101814,sc106,tc1056,left_only,Columbia Explorers Elementary Academy,"Fitzner, Jillian"
76152,sc106,tc1069,both,Columbia Explorers Elementary Academy,"Grosskopf, Denise"
153086,sc106,tc1113,both,Columbia Explorers Elementary Academy,"Medina, Bernice"
...,...,...,...,...,...
262090,sc143,tc1063,both,South Shore Fine Arts Academy,"Georgiou, Melissa"
558852,sc143,tc1146,right_only,South Shore Fine Arts Academy,"Regan, Abigale"
102151,sc143,tc1149,both,South Shore Fine Arts Academy,"Rhyne, Tarsia"
38656,sc143,tc1163,both,South Shore Fine Arts Academy,"Sabbath, Natalie"
152913,sc143,tc1209,left_only,South Shore Fine Arts Academy,"Yang, Geo"
559398,sc144,tc1047,right_only,Spencer Elementary Technology Academy,"Dixon, Brittani"
429518,sc144,tc1071,both,Spencer Elementary Technology Academy,"Hall, Latrice"
559043,sc144,tc1134,right_only,Spencer Elementary Technology Academy,"Phillips, Jala"
429438,sc144,tc1182,left_only,Spencer Elementary Technology Academy,"Spencer, Geogetta"
559991,sc145,tc1067,right_only,Talcott Fine Arts and Museum Academy,"Granados, Rosalba"
560407,sc145,tc1099,right_only,Talcott Fine Arts and Museum Academy,"Livering, Alyssa"
560014,sc145,tc1168,right_only,Talcott Fine Arts and Museum Academy,"Sanchez, Wendolyne"
229429,sc146,tc1089,left_only,UCSN Roberto Clemente,"Kirby, Kristin"
315681,sc146,tc1104,left_only,UCSN Roberto Clemente,"Mansell, Claire"
389049,sc146,tc1108,left_only,UCSN Roberto Clemente,"Masciola, Stacy"
229302,sc146,tc1132,left_only,UCSN Roberto Clemente,"Pall, Jami"
315725,sc146,tc1136,left_only,UCSN Roberto Clemente,"Poteshman, Danielle"
389048,sc146,tc1176,left_only,UCSN Roberto Clemente,"Siegel, Dana"
496392,sc147,tc1009,both,Wendell Smith Elementary School,"Barnes, Kendra"
511316,sc147,tc1078,both,Wendell Smith Elementary School,"Jacobsen, Kimberly"
545320,sc147,tc1154,both,Wendell Smith Elementary School,"Robinson, Zulekha"
562278,sc148,tc1090,right_only,Willa Cather Elementary School,"Kolar, Fatima"
325043,sc149,tc1027,both,Woodlawn Community School,"Chambers-Jeter, Joi"
558921,sc149,tc1079,right_only,Woodlawn Community School,"Jefferson, Lindsay"
101975,sc149,tc1164,left_only,Woodlawn Community School,"Salahuddin, Renee"
283605,sc150,tc1032,both,Woodson South Elementary School,"Condon, Emily"
429361,sc150,tc1162,left_only,Woodson South Elementary School,"Ryan, Renee"
293445,sc150,tc1173,left_only,Woodson South Elementary School,"Scott, Ikyta"
559262,sc150,tc1200,right_only,Woodson South Elementary School,"Washington, Cherry"
558653,NaN,tc1064,right_only,NaN,"Gibson, Stacy"

In [358]:
fy18_19['_merge']=np.where(fy18_19['_merge']=='left_only', 'sy18', fy18_19['_merge'])
fy18_19['_merge']=np.where(fy18_19['_merge']=='right_only', 'sy19', fy18_19['_merge'])

In [359]:
fy18_19.reindex(columns=['SchoolName','sch_id','TeacherName','tch_id','_merge']).to_csv('/Users/snigd/Desktop/Dropbox/UIC Data Project/Working/tables/teacher_table.csv', 
                                                                                index=False, header=True)

##### Creating a list of unique coaches

In [378]:
CoachNamesfy18=fy18['Coach'].tolist()
CoachNamesfy19=fy19['Coach'].tolist()
print (len(list(set(CoachNamesfy18))))
print (len(list(set(CoachNamesfy19))))

6
8

In [379]:
CoachNames = set(CoachNamesfy18 + CoachNamesfy19)
CoachN=list(CoachNames)
Coach_table=pd.DataFrame(CoachN, columns=['CoachName'])
Coach_table=Coach_table.dropna()
Coach_table=Coach_table.sort_values(['CoachName'])
#print (len(teacher_table))
(Coach_table)

             CoachName
4      Jackson, Little
8  Johnston, Elizabeth
6      Lepeley, Karina
2        McManus, Lisa
3         Menke, Becca
5        Randruut, Avo
7       Telman, Ashley
1        Thomas, Jamie

##### Merging the coach table with the updated fy18 dataset that includes school id and teacher id

In [380]:
Coach_table['coach_id'] = (Coach_table.groupby(['CoachName']).cumcount()==0).astype(int)
Coach_table['coach_id'] = Coach_table['coach_id'].cumsum()
Coach_table

             CoachName  coach_id
4      Jackson, Little         1
8  Johnston, Elizabeth         2
6      Lepeley, Karina         3
2        McManus, Lisa         4
3         Menke, Becca         5
5        Randruut, Avo         6
7       Telman, Ashley         7
1        Thomas, Jamie         8

In [381]:
Coach_table['initials']=np.where(Coach_table['coach_id']<10, 'c10','c1')
Coach_table['coach_id']= Coach_table['initials'] + Coach_table.coach_id.map(str)
Coach_table

             CoachName coach_id initials
4      Jackson, Little     c101      c10
8  Johnston, Elizabeth     c102      c10
6      Lepeley, Karina     c103      c10
2        McManus, Lisa     c104      c10
3         Menke, Becca     c105      c10
5        Randruut, Avo     c106      c10
7       Telman, Ashley     c107      c10
1        Thomas, Jamie     c108      c10

In [382]:
fy18_tchid.rename({'Coach':'CoachName'}, axis='columns', inplace = True)

In [383]:
fy18_coach=pd.merge(fy18_tchid, Coach_table[['CoachName','coach_id']], on='CoachName',how='left', indicator=True)
fy18_coach.groupby('_merge')['CoachName'].nunique()

_merge
left_only     0
right_only    0
both          6
Name: CoachName, dtype: int64

In [386]:
fy18_coach=fy18_coach.drop(['_merge'],axis=1)

In [384]:
fy19_tchid.rename({'Coach':'CoachName'}, axis='columns', inplace = True)

In [385]:
fy19_coach=pd.merge(fy19_tchid, Coach_table[['CoachName','coach_id']], on='CoachName',how='left', indicator=True)
fy19_coach.groupby('_merge')['CoachName'].nunique()

_merge
left_only     0
right_only    0
both          7
Name: CoachName, dtype: int64

In [387]:
fy19_coach=fy19_coach.drop(['_merge'],axis=1)

##### Merging updated fy 18 and 19 data and keeping only school, teacher andcoach columns

In [390]:
fy18_19Coach=pd.merge(fy18_coach[['SchoolName','sch_id','TeacherName','tch_id','CoachName', 'coach_id']],
                      fy19_coach[['SchoolName','sch_id','TeacherName','tch_id','CoachName','coach_id']]
                , on = ['SchoolName','sch_id','TeacherName','tch_id','CoachName', 'coach_id','sch_id','tch_id','coach_id'], how='outer', indicator=True)

In [392]:
fy18_19Coach['_merge']=np.where(fy18_19Coach['_merge']=='left_only', 'sy18', fy18_19Coach['_merge'])
fy18_19Coach['_merge']=np.where(fy18_19Coach['_merge']=='right_only', 'sy19', fy18_19Coach['_merge'])

,SchoolName,sch_id,TeacherName,tch_id,CoachName,coach_id,_merge
0,Shoesmith,sc141,"Hobson, Ashley",tc1074,"Randruut, Avo",c106,sy18
1,Shoesmith,sc141,"Hobson, Ashley",tc1074,"Randruut, Avo",c106,sy18
2,Shoesmith,sc141,"Hobson, Ashley",tc1074,"Randruut, Avo",c106,sy18
3,Shoesmith,sc141,"Hobson, Ashley",tc1074,"Randruut, Avo",c106,sy18
4,Shoesmith,sc141,"Hobson, Ashley",tc1074,"Randruut, Avo",c106,sy18
5,Shoesmith,sc141,"Hobson, Ashley",tc1074,"Randruut, Avo",c106,sy18
6,Shoesmith,sc141,"Hobson, Ashley",tc1074,"Randruut, Avo",c106,sy18
7,Shoesmith,sc141,"Hobson, Ashley",tc1074,"Randruut, Avo",c106,sy18
8,Shoesmith,sc141,"Hobson, Ashley",tc1074,"Randruut, Avo",c106,sy18
9,Shoesmith,sc141,"Hobson, Ashley",tc1074,"Randruut, Avo",c106,sy18
10,Shoesmith,sc141,"Hobson, Ashley",tc1074,"Randruut, Avo",c106,sy18
11,Shoesmith,sc141,"Hobson, Ashley",tc1074,"Randruut, Avo",c106,sy18
12,Shoesmith,sc141,"Hobson, Ashley",tc1074,"Randruut, Avo",c106,sy18
13,Shoesmith,sc141,"Hobson, Ashley",tc1074,"Randruut, Avo",c106,sy18
14,Shoesmith,sc141,"Hobson, Ashley",tc1074,"Randruut, Avo",c106,sy18
15,Shoesmith,sc141,"Hobson, Ashley",tc1074,"Randruut, Avo",c106,sy18
16,Shoesmith,sc141,"Hobson, Ashley",tc1074,"Randruut, Avo",c106,sy18
17,Shoesmith,sc141,"Hobson, Ashley",tc1074,"Randruut, Avo",c106,sy18
18,Shoesmith,sc141,"Hobson, Ashley",tc1074,"Randruut, Avo",c106,sy18
19,Shoesmith,sc141,"Hobson, Ashley",tc1074,"Randruut, Avo",c106,sy18
20,Shoesmith,sc141,"Hobson, Ashley",tc1074,"Randruut, Avo",c106,sy18
21,Shoesmith,sc141,"Hobson, Ashley",tc1074,"Randruut, Avo",c106,sy18
22,Shoesmith,sc141,"Hobson, Ashley",tc1074,"Randruut, Avo",c106,sy18
23,Shoesmith,sc141,"Hobson, Ashley",tc1074,"Randruut, Avo",c106,sy18
24,Shoesmith,sc141,"Hobson, Ashley",tc1074,"Randruut, Avo",c106,sy18
25,Shoesmith,sc141,"Hobson, Ashley",tc1074,"Randruut, Avo",c106,sy18
26,Shoesmith,sc141,"Hobson, Ashley",tc1074,"Randruut, Avo",c106,sy18
27,Shoesmith,sc141,"Hobson, Ashley",tc1074,"Randruut, Avo",c106,sy18
28,Shoesmith,sc141,"Hobson, Ashley",tc1074,"Randruut, Avo",c106,sy18
29,Shoesmith,sc141,"Hobson, Ashley",tc1074,"Randruut, Avo",c106,sy18
...,...,...,...,...,...,...,...
334373,Dr. Marting L. King Jr. Academy of Social Justice,sc108,"Williams, Odessa",tc1205,"Jackson, Little",c101,sy19
334374,Dr. Marting L. King Jr. Academy of Social Justice,sc108,"Williams, Odessa",tc1205,"Jackson, Little",c101,sy19
334375,Dr. Marting L. King Jr. Academy of Social Justice,sc108,"Williams, Odessa",tc1205,"Jackson, Little",c101,sy19
334376,Dr. Marting L. King Jr. Academy of Social Justice,sc108,"Williams, Odessa",tc1205,"Jackson, Little",c101,sy19
334377,Dr. Marting L. King Jr. Academy of Social Justice,sc108,"Williams, Odessa",tc1205,"Jackson, Little",c101,sy19
334378,Dr. Marting L. King Jr. Academy of Social Justice,sc108,"Williams, Odessa",tc1205,"Jackson, Little",c101,sy19
334379,Dr. Marting L. King Jr. Academy of Social Justice,sc108,"Williams, Odessa",tc1205,"Jackson, Little",c101,sy19
334380,Dr. Marting L. King Jr. Academy of Social Justice,sc108,"Williams, Odessa",tc1205,"Jackson, Little",c101,sy19
334381,Dr. Marting L. King Jr. Academy of Social Justice,sc108,"Williams, Odessa",tc1205,"Jackson, Little",c101,sy19
334382,Dr. Marting L. King Jr. Academy of Social Justice,sc108,"Williams, Odessa",tc1205,"Jackson, Little",c101,sy19
334383,Dr. Marting L. King Jr. Academy of Social Justice,sc108,"Williams, Odessa",tc1205,"Jackson, Little",c101,sy19
334384,Dr. Marting L. King Jr. Academy of Social Justice,sc108,"Williams, Odessa",tc1205,"Jackson, Little",c101,sy19
334385,Dr. Marting L. King Jr. Academy of Social Justice,sc108,"Williams, Odessa",tc1205,"Jackson, Little",c101,sy19
334386,Dr. Marting L. King Jr. Academy of Social Justice,sc108,"Williams, Odessa",tc1205,"Jackson, Little",c101,sy19
334387,Dr. Marting L. King Jr. Academy of Social Justice,sc108,"Williams, Odessa",tc1205,"Jackson, Little",c101,sy19
334388,Dr. Marting L. King Jr. Academy of Social Justice,sc108,"Williams, Odessa",tc1205,"Jackson, Little",c101,sy19
334389,Dr. Marting L. King Jr. Academy of Social Justice,sc108,"Williams, Odessa",tc1205,"Jackson, Little",c101,sy19
334390,Dr. Marting L. King Jr. Academy of Social Justice,sc108,"Williams, Odessa",tc1205,"Jackson, Little",c101,sy19
334391,Dr. Marting L. King Jr. Academy of Social Justice,sc108,"Williams, Odessa",tc1205,"Jackson, Little",c101,sy19
334392,Dr. Marting L. King Jr. Academy of Social Justice,sc108,"Williams, Odessa",tc1205,"Jackson, Little",c101,sy19
334393,Dr. Marting L. King Jr. Academy of Social Justice,sc108,"Williams, Odessa",tc1205,"Jackson, Little",c101,sy19
334394,Dr. Marting L. King Jr. Academy of Social Justice,sc108,"Williams, Odessa",tc1205,"Jackson, Little",c101,sy19
334395,Dr. Marting L. King Jr. Academy of Social Justice,sc108,"Williams, Odessa",tc1205,"Jackson, Little",c101,sy19
334396,Dr. Marting L. King Jr. Academy of Social Justice,sc108,"Williams, Odessa",tc1205,"Jackson, Little",c101,sy19
334397,Dr. Marting L. King Jr. Academy of Social Justice,sc108,"Williams, Odessa",tc1205,"Jackson, Little",c101,sy19
334398,Dr. Marting L. King Jr. Academy of Social Justice,sc108,"Williams, Odessa",tc1205,"Jackson, Little",c101,sy19
334399,Dr. Marting L. King Jr. Academy of Social Justice,sc108,"Williams, Odessa",tc1205,"Jackson, Little",c101,sy19
334400,Dr. Marting L. King Jr. Academy of Social Justice,sc108,"Williams, Odessa",tc1205,"Jackson, Little",c101,sy19
334401,Dr. Marting L. King Jr. Academy of Social Justice,sc108,"Williams, Odessa",tc1205,"Jackson, Little",c101,sy19
334402,Dr. Marting L. King Jr. Academy of Social Justice,sc108,"Williams, Odessa",tc1205,"Jackson, Little",c101,sy19

In [394]:
fy18_19Coach.drop_duplicates(subset=['sch_id','tch_id', 'coach_id'],keep='first', inplace=True)
fy18_19Coach.sort_values(['sch_id','tch_id', 'coach_id'])

,SchoolName,sch_id,TeacherName,tch_id,CoachName,coach_id,_merge
328437,Alfred Nobel Elementary School,sc101,"Cardona, Elsa",tc1022,"Johnston, Elizabeth",c102,sy19
77276,Alfred Nobel Elementary School,sc101,"Cardona, Elsa",tc1022,"Menke, Becca",c105,sy18
328656,Alfred Nobel Elementary School,sc101,"Contreras, Jasmine",tc1034,"Johnston, Elizabeth",c102,sy19
77632,Alfred Nobel Elementary School,sc101,"Contreras, Jasmine",tc1034,"McManus, Lisa",c104,sy18
327978,Alfred Nobel Elementary School,sc101,"Kolasa, Susi",tc1091,"Johnston, Elizabeth",c102,sy19
63539,Alfred Nobel Elementary School,sc101,"Kolasa, Susi",tc1091,"Menke, Becca",c105,sy18
328347,Alfred Nobel Elementary School,sc101,"McCarter, Lisa",tc1111,"Johnston, Elizabeth",c102,sy19
77198,Alfred Nobel Elementary School,sc101,"McCarter, Lisa",tc1111,"McManus, Lisa",c104,sy18
71134,Alfred Nobel Elementary School,sc101,"Romano, Nikki",tc1160,"McManus, Lisa",c104,sy18
331383,Alfred Nobel Elementary School,sc101,"Salgado, Yaneli",tc1165,"Johnston, Elizabeth",c102,sy19
213840,Alfred Nobel Elementary School,sc101,"Tzoumas, Nicole",tc1193,"McManus, Lisa",c104,sy18
331580,Alfred Nobel Elementary School,sc101,"Wall, Mary",tc1197,"Johnston, Elizabeth",c102,sy19
214109,Bret Harte Elementary,sc102,"Grib, Megan",tc1068,"Lepeley, Karina",c103,sy18
329686,Bret Harte Elementary,sc102,"Grib, Megan",tc1068,"McManus, Lisa",c104,sy19
214234,Bret Harte Elementary,sc102,"Mitchell, Faith",tc1118,"Lepeley, Karina",c103,sy18
329809,Bret Harte Elementary,sc102,"Mitchell, Faith",tc1118,"McManus, Lisa",c104,sy19
231976,Carver Primary School,sc103,"Boyland, Maxine",tc1015,"Jackson, Little",c101,sy18
232085,Carver Primary School,sc103,"Turner, Katherine",tc1192,"Jackson, Little",c101,sy18
307518,Charles W. Earle Elementary,sc104,"Funches, Shatara",tc1059,"Jackson, Little",c101,both
313346,Charles W. Earle Elementary,sc104,"Henderson, Teresa",tc1072,"Jackson, Little",c101,sy18
331816,Charles W. Earle Elementary,sc104,"Jiang, Diana",tc1080,"Jackson, Little",c101,sy19
313419,Charles W. Earle Elementary,sc104,"Power, Gabrielle",tc1137,"Jackson, Little",c101,sy18
54602,Charles W. Earle Elementary,sc104,"Sims, Tonya",tc1178,"Jackson, Little",c101,sy18
328564,Cleveland,sc105,"Gomez, Priscilla",tc1065,"Jackson, Little",c101,sy19
77515,Cleveland,sc105,"Gomez, Priscilla",tc1065,"McManus, Lisa",c104,sy18
327188,Cleveland,sc105,"Rivera, Maricela",tc1151,"Jackson, Little",c101,sy19
1876,Cleveland,sc105,"Rivera, Maricela",tc1151,"McManus, Lisa",c104,sy18
327543,Cleveland,sc105,"Watson, Gretchen",tc1201,"Jackson, Little",c101,sy19
2120,Cleveland,sc105,"Watson, Gretchen",tc1201,"McManus, Lisa",c104,sy18
327077,Cleveland,sc105,"Wren, Amanda",tc1208,"Jackson, Little",c101,sy19
...,...,...,...,...,...,...,...
327888,South Shore Fine Arts Academy,sc143,"Rhyne, Tarsia",tc1149,"Jackson, Little",c101,sy19
54686,South Shore Fine Arts Academy,sc143,"Rhyne, Tarsia",tc1149,"Johnston, Elizabeth",c102,sy18
327655,South Shore Fine Arts Academy,sc143,"Sabbath, Natalie",tc1163,"Jackson, Little",c101,sy19
6379,South Shore Fine Arts Academy,sc143,"Sabbath, Natalie",tc1163,"Johnston, Elizabeth",c102,sy18
71240,South Shore Fine Arts Academy,sc143,"Yang, Geo",tc1209,"Johnston, Elizabeth",c102,sy18
330663,Spencer Elementary Technology Academy,sc144,"Dixon, Brittani",tc1047,"McManus, Lisa",c104,sy19
214468,Spencer Elementary Technology Academy,sc144,"Hall, Latrice",tc1071,"McManus, Lisa",c104,both
330308,Spencer Elementary Technology Academy,sc144,"Phillips, Jala",tc1134,"McManus, Lisa",c104,sy19
214388,Spencer Elementary Technology Academy,sc144,"Spencer, Geogetta",tc1182,"McManus, Lisa",c104,sy18
331256,Talcott Fine Arts and Museum Academy,sc145,"Granados, Rosalba",tc1067,"Menke, Becca",c105,sy19
331672,Talcott Fine Arts and Museum Academy,sc145,"Livering, Alyssa",tc1099,"McManus, Lisa",c104,sy19
331279,Talcott Fine Arts and Museum Academy,sc145,"Sanchez, Wendolyne",tc1168,"Menke, Becca",c105,sy19
109524,UCSN Roberto Clemente,sc146,"Kirby, Kristin",tc1089,"McManus, Lisa",c104,sy18
144741,UCSN Roberto Clemente,sc146,"Mansell, Claire",tc1104,"McManus, Lisa",c104,sy18
209303,UCSN Roberto Clemente,sc146,"Masciola, Stacy",tc1108,"McManus, Lisa",c104,sy18
109397,UCSN Roberto Clemente,sc146,"Pall, Jami",tc1132,"McManus, Lisa",c104,sy18
144785,UCSN Roberto Clemente,sc146,"Poteshman, Danielle",tc1136,"McManus, Lisa",c104,sy18
209302,UCSN Roberto Clemente,sc146,"Siegel, Dana",tc1176,"McManus, Lisa",c104,sy18
281342,Wendell Smith Elementary School,sc147,"Barnes, Kendra",tc1009,"McManus, Lisa",c104,both
296266,Wendell Smith Elementary School,sc147,"Jacobsen, Kimberly",tc1078,"McManus, Lisa",c104,both
313874,Wendell Smith Elementary School,sc147,"Robinson, Zulekha",tc1154,"McManus, Lisa",c104,both
333543,Willa Cather Elementary School,sc148,"Kolar, Fatima",tc1090,"Thomas, Jamie",c108,sy19
145297,Woodlawn Community School,sc149,"Chambers-Jeter, Joi",tc1027,"Jackson, Little",c101,both
330186,Woodlawn Community School,sc149,"Jefferson, Lindsay",tc1079,"Jackson, Little",c101,sy19
54510,Woodlawn Community School,sc149,"Salahuddin, Renee",tc1164,"Jackson, Little",c101,sy18
118365,Woodson South Elementary School,sc150,"Condon, Emily",tc1032,"Jackson, Little",c101,both
214311,Woodson South Elementary School,sc150,"Ryan, Renee",tc1162,"Jackson, Little",c101,sy18
128205,Woodson South Elementary School,sc150,"Scott, Ikyta",tc1173,"Jackson, Little",c101,sy18
330527,Woodson South Elementary School,sc150,"Washington, Cherry",tc1200,"Jackson, Little",c101,sy19
327465,NaN,NaN,"Gibson, Stacy",tc1064,"Johnston, Elizabeth",c102,sy19

In [395]:
fy18_19Coach.to_csv('/Users/snigd/Desktop/Dropbox/UIC Data Project/Working/tables/coach_table.csv', 
                                                                                index=False, header=True)