In [144]:
import pandas as pd
import os
import numpy as np

In [145]:
fy18=pd.read_csv("/Users/snigd/Desktop/Dropbox/UIC Data Project/Working/fy18 eoy data chicago.csv", encoding = 'utf8')
fy19=pd.read_csv("/Users/snigd/Desktop/Dropbox/UIC Data Project/Working/Chicagofy19eoyrawdata with descriptions.csv", encoding ='utf8')

In [146]:
fy18.rename({'School_FullName':'SchoolName', 'Teacher': 'TeacherName', 'Coach':'CoachName', 
              'GradeLevel_FullName':'GradeLevel_FullName_18'},axis='columns', inplace = True)

In [147]:
coachtable=pd.read_csv("coach_table.csv")
coachtable=coachtable.drop(['_merge'],axis=1)

In [148]:
fy18id=pd.merge(fy18,coachtable, on=['SchoolName', 'TeacherName','CoachName'], how='left', indicator=True)

In [149]:
fy18id.groupby('_merge')['CoachName'].nunique()

_merge
left_only     0
right_only    0
both          6
Name: CoachName, dtype: int64

In [150]:
fy18id=fy18id.drop(['_merge'], axis=1)

In [151]:
studenttable=pd.read_csv("student_table.csv")

In [152]:
fy18id=pd.merge(fy18id,studenttable[['sch_id','Student','student_id','GradeLevel_FullName_18']], 
                on=['sch_id','GradeLevel_FullName_18','Student'], how='left', indicator=True)

In [153]:
fy18id.groupby('_merge')['Student'].nunique()

_merge
left_only        0
right_only       0
both          3553
Name: Student, dtype: int64

In [154]:
fy18e=fy18id[(fy18id['Language Name']=='English') & (fy18id['GradeLevel_FullName_18']=='Kindergarten')]

In [155]:
fy18e=fy18e[['SchoolName','sch_id', 'TeacherName','tch_id', 'CoachName','coach_id','GradeLevel_FullName_18','Student',
             'student_id','TestTypeCode','BOY','SEP','OCT','NOV','DEC','MOY','JAN','FEB','Mar','APR','EOY']]

In [156]:
#fy18e[['BOY','SEP','OCT','NOV','DEC','MOY','JAN','FEB','Mar','APR','EOY']]=fy18e[['BOY','SEP','OCT','NOV','DEC','MOY',
                                                                                  'JAN','FEB','Mar','APR','EOY']].fillna('')

IndentationError: unexpected indent (<ipython-input-156-ad6dc86caad3>, line 2)

In [157]:
fy18e

,SchoolName,sch_id,TeacherName,tch_id,CoachName,coach_id,GradeLevel_FullName_18,Student,student_id,TestTypeCode,...,SEP,OCT,NOV,DEC,MOY,JAN,FEB,Mar,APR,EOY
0,Shoesmith,sc142,"Hobson, Ashley",tc1074,"Randruut, Avo",c106,Kindergarten,"Buchanan, Ma'kayla Eternity",st0001,FSF,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Shoesmith,sc142,"Hobson, Ashley",tc1074,"Randruut, Avo",c106,Kindergarten,"Howard, Jamayle Christopher",st0002,FSF,...,NaN,24.0,NaN,NaN,38.0,NaN,NaN,NaN,NaN,NaN
2,Shoesmith,sc142,"Hobson, Ashley",tc1074,"Randruut, Avo",c106,Kindergarten,"Howard, Jamayle Christopher",st0002,NWF-CLS,...,NaN,NaN,NaN,NaN,19.0,NaN,NaN,NaN,NaN,51.0
4,Shoesmith,sc142,"Hobson, Ashley",tc1074,"Randruut, Avo",c106,Kindergarten,"Howard, Jamayle Christopher",st0002,PSF,...,NaN,NaN,NaN,NaN,56.0,NaN,NaN,67.0,NaN,61.0
5,Shoesmith,sc142,"Hobson, Ashley",tc1074,"Randruut, Avo",c106,Kindergarten,"Douse, A'Niyah Marie",st0003,FSF,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Shoesmith,sc142,"Hobson, Ashley",tc1074,"Randruut, Avo",c106,Kindergarten,"Peters, Kameron Demil",st0004,FSF,...,NaN,35.0,NaN,NaN,39.0,NaN,NaN,NaN,NaN,NaN
7,Shoesmith,sc142,"Hobson, Ashley",tc1074,"Randruut, Avo",c106,Kindergarten,"Peters, Kameron Demil",st0004,NWF-CLS,...,NaN,NaN,NaN,NaN,27.0,NaN,NaN,NaN,NaN,43.0
9,Shoesmith,sc142,"Hobson, Ashley",tc1074,"Randruut, Avo",c106,Kindergarten,"Peters, Kameron Demil",st0004,PSF,...,NaN,NaN,NaN,NaN,62.0,NaN,NaN,71.0,NaN,63.0
10,Shoesmith,sc142,"Hobson, Ashley",tc1074,"Randruut, Avo",c106,Kindergarten,"Hamilton, Madison Brielle",st0005,FSF,...,NaN,27.0,NaN,NaN,41.0,NaN,NaN,NaN,NaN,NaN
11,Shoesmith,sc142,"Hobson, Ashley",tc1074,"Randruut, Avo",c106,Kindergarten,"Hamilton, Madison Brielle",st0005,NWF-CLS,...,NaN,NaN,NaN,NaN,25.0,NaN,NaN,NaN,NaN,36.0
13,Shoesmith,sc142,"Hobson, Ashley",tc1074,"Randruut, Avo",c106,Kindergarten,"Hamilton, Madison Brielle",st0005,PSF,...,NaN,NaN,NaN,NaN,51.0,NaN,NaN,67.0,NaN,60.0
14,Shoesmith,sc142,"Hobson, Ashley",tc1074,"Randruut, Avo",c106,Kindergarten,"Hervey, Amar'e Felan",st0006,FSF,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,Shoesmith,sc142,"Hobson, Ashley",tc1074,"Randruut, Avo",c106,Kindergarten,"Coles, Journie",st0007,FSF,...,NaN,NaN,NaN,NaN,41.0,NaN,NaN,NaN,NaN,NaN
16,Shoesmith,sc142,"Hobson, Ashley",tc1074,"Randruut, Avo",c106,Kindergarten,"Coles, Journie",st0007,NWF-CLS,...,NaN,NaN,NaN,NaN,44.0,NaN,NaN,NaN,NaN,55.0
18,Shoesmith,sc142,"Hobson, Ashley",tc1074,"Randruut, Avo",c106,Kindergarten,"Coles, Journie",st0007,PSF,...,NaN,NaN,NaN,NaN,17.0,NaN,NaN,14.0,NaN,69.0
19,Shoesmith,sc142,"Hobson, Ashley",tc1074,"Randruut, Avo",c106,Kindergarten,"Marshall, Mason",st0008,FSF,...,NaN,26.0,NaN,NaN,44.0,NaN,NaN,NaN,NaN,NaN
20,Shoesmith,sc142,"Hobson, Ashley",tc1074,"Randruut, Avo",c106,Kindergarten,"Marshall, Mason",st0008,NWF-CLS,...,NaN,NaN,NaN,NaN,32.0,NaN,NaN,NaN,NaN,45.0
22,Shoesmith,sc142,"Hobson, Ashley",tc1074,"Randruut, Avo",c106,Kindergarten,"Marshall, Mason",st0008,PSF,...,NaN,NaN,NaN,NaN,55.0,NaN,NaN,51.0,NaN,58.0
23,Shoesmith,sc142,"Hobson, Ashley",tc1074,"Randruut, Avo",c106,Kindergarten,"KYEI, NASIR",st0009,FSF,...,NaN,0.0,NaN,NaN,18.0,NaN,NaN,21.0,NaN,NaN
24,Shoesmith,sc142,"Hobson, Ashley",tc1074,"Randruut, Avo",c106,Kindergarten,"KYEI, NASIR",st0009,NWF-CLS,...,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,33.0
26,Shoesmith,sc142,"Hobson, Ashley",tc1074,"Randruut, Avo",c106,Kindergarten,"KYEI, NASIR",st0009,PSF,...,NaN,NaN,NaN,NaN,19.0,NaN,NaN,15.0,NaN,19.0
27,Shoesmith,sc142,"Hobson, Ashley",tc1074,"Randruut, Avo",c106,Kindergarten,"Webb-Arrieta, Kyrie B",st0010,FSF,...,NaN,23.0,NaN,NaN,27.0,NaN,NaN,NaN,NaN,NaN
28,Shoesmith,sc142,"Hobson, Ashley",tc1074,"Randruut, Avo",c106,Kindergarten,"Webb-Arrieta, Kyrie B",st0010,NWF-CLS,...,NaN,NaN,NaN,NaN,33.0,NaN,NaN,NaN,NaN,63.0
30,Shoesmith,sc142,"Hobson, Ashley",tc1074,"Randruut, Avo",c106,Kindergarten,"Webb-Arrieta, Kyrie B",st0010,PSF,...,NaN,NaN,NaN,NaN,14.0,NaN,NaN,25.0,NaN,65.0
31,Shoesmith,sc142,"Hobson, Ashley",tc1074,"Randruut, Avo",c106,Kindergarten,"Harper, Anthony J",st0011,FSF,...,NaN,20.0,NaN,NaN,40.0,NaN,NaN,NaN,NaN,NaN
32,Shoesmith,sc142,"Hobson, Ashley",tc1074,"Randruut, Avo",c106,Kindergarten,"Harper, Anthony J",st0011,NWF-CLS,...,NaN,NaN,NaN,NaN,41.0,NaN,NaN,NaN,NaN,47.0
34,Shoesmith,sc142,"Hobson, Ashley",tc1074,"Randruut, Avo",c106,Kindergarten,"Harper, Anthony J",st0011,PSF,...,NaN,NaN,NaN,NaN,29.0,NaN,NaN,70.0,NaN,60.0
35,Shoesmith,sc142,"Hobson, Ashley",tc1074,"Randruut, Avo",c106,Kindergarten,"Hethington, Leelah Riyan",st0012,FSF,...,NaN,34.0,NaN,NaN,54.0,NaN,NaN,NaN,NaN,NaN
36,Shoesmith,sc142,"Hobson, Ashley",tc1074,"Randruut, Avo",c106,Kindergarten,"Hethington, Leelah Riyan",st0012,NWF-CLS,...,NaN,NaN,NaN,NaN,29.0,NaN,NaN,NaN,NaN,39.0
38,Shoesmith,sc142,"Hobson, Ashley",tc1074,"Randruut, Avo",c106,Kindergarten,"Hethington, Leelah Riyan",st0012,PSF,...,NaN,NaN,NaN,NaN,16.0,NaN,NaN,61.0,NaN,71.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12388,Wendell Smith Elementary School,sc148,"Robinson, Zulekha",tc1154,"McManus, Lisa",c104,Kindergarten,"Butler, Jayden",st1818,NWF-CLS,...,NaN,NaN,NaN,NaN,9.0,NaN,NaN,NaN,NaN,NaN
12390,Wendell Smith Elementary School,sc148,"Robinson, Zulekha",tc1154,"McManus, Lisa",c104,Kindergarten,"Butler, Jayden",st1818,PSF,...,NaN,NaN,NaN,NaN,36.0,NaN,NaN,61.0,NaN,72.0
12391,Wendell Smith Elementary School,sc148,"Robinson, Zulekha",tc1154,"McManus, Lisa",c104,Kindergarten,"Johnson, Deshon",st1820,FSF,...,NaN,NaN,NaN,NaN,24.0,NaN,NaN,NaN,NaN,NaN
12392,Wendell Smith Elementary School,sc148,"Robinson, Zulekha",tc1154,"McManus, Lisa",c104,Kindergarten,"Johnson, Deshon",st1820,NWF-CLS,...,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN
12394,Wendell Smith Elementary School,sc148,"Robinson, Zulekha",tc1154,"McManus, Lisa",c104,Kindergarten,"Johnson, Deshon",st1820,PSF,...,NaN,NaN,NaN,NaN,1.0,NaN,NaN,23.0,NaN,60.0
12395,Wendell Smith Elementary School,sc148,"Robinson, Zulekha",tc1154,"McManus, Lisa",c104,Kindergarten,"Rockett, Olivyah",st1824,FSF,...,NaN,NaN,NaN,NaN,31.0,NaN,NaN,NaN,NaN,NaN
12396,Wendell Smith Elementary School,sc148,"Robinson, Zulekha",tc1154,"McManus, Lisa",c104,Kindergarten,"Rockett, Olivyah",st1824,NWF-CLS,...,NaN,NaN,NaN,NaN,17.0,NaN,NaN,NaN,NaN,NaN
12398,Wendell Smith Elementary School,sc148,"Robinson, Zulekha",tc1154,"McManus, Lisa",c104,Kindergarten,"Rockett, Olivyah",st1824,PSF,...,NaN,NaN,NaN,NaN,11.0,NaN,NaN,55.0,NaN,62.0
12399,Wendell Smith Elementary School,sc148,"Robinson, Zulekha",tc1154,"McManus, Lisa",c104,Kindergarten,"MATTHEWS, MARQUITA",st1840,FSF,...,NaN,NaN,NaN,NaN,53.0,NaN,NaN,NaN,NaN,NaN
12400,Wendell Smith Elementary School,sc148,"Robinson, Zulekha",tc1154,"McManus, Lisa",c104,Kindergarten,"MATTHEWS, MARQUITA",st1840,NWF-CLS,...,NaN,NaN,NaN,NaN,13.0,NaN,NaN,NaN,NaN,NaN
12402,Wendell Smith Elementary School,sc148,"Robinson, Zulekha",tc1154,"McManus, Lisa",c104,Kindergarten,"MATTHEWS, MARQUITA",st1840,PSF,...,NaN,NaN,NaN,NaN,25.0,NaN,NaN,41.0,NaN,53.0
12403,Wendell Smith Elementary School,sc148,"Robinson, Zulekha",tc1154,"McManus, Lisa",c104,Kindergarten,"Madison, Javariah",st1826,FSF,...,NaN,NaN,NaN,NaN,41.0,NaN,NaN,NaN,NaN,NaN
12404,Wendell Smith Elementary School,sc148,"Robinson, Zulekha",tc1154,"McManus, Lisa",c104,Kindergarten,"Madison, Javariah",st1826,NWF-CLS,...,NaN,NaN,NaN,NaN,16.0,NaN,NaN,NaN,NaN,NaN
12406,Wendell Smith Elementary School,sc148,"Robinson, Zulekha",tc1154,"McManus, Lisa",c104,Kindergarten,"Madison, Javariah",st1826,PSF,...,NaN,NaN,NaN,NaN,52.0,NaN,NaN,70.0,NaN,50.0
12407,Wendell Smith Elementary School,sc148,"Robinson, Zulekha",tc1154,"McManus, Lisa",c104,Kindergarten,"McClendon, Riley",st1830,FSF,...,NaN,NaN,NaN,NaN,51.0,NaN,NaN,NaN,NaN,NaN
12408,Wendell Smith Elementary School,sc148,"Robinson, Zulekha",tc1154,"McManus, Lisa",c104,Kindergarten,"McClendon, Riley",st1830,NWF-CLS,...,NaN,NaN,NaN,NaN,14.0,NaN,NaN,NaN,NaN,NaN
12410,Wendell Smith Elementary School,sc148,"Robinson, Zulekha",tc1154,"McManus, Lisa",c104,Kindergarten,"McClendon, Riley",st1830,PSF,...,NaN,NaN,NaN,NaN,8.0,NaN,NaN,NaN,NaN,NaN
12411,Wendell Smith Elementary School,sc148,"Robinson, Zulekha",tc1154,"McManus, Lisa",c104,Kindergarten,"Harris, Jayda A",st1833,FSF,...,NaN,NaN,NaN,NaN,46.0,NaN,NaN,NaN,NaN,NaN
12412,Wendell Smith Elementary School,sc148,"Robinson, Zulekha",tc1154,"McManus, Lisa",c104,Kindergarten,"Harris, Jayda A",st1833,NWF-CLS,...,NaN,NaN,NaN,NaN,24.0,NaN,NaN,NaN,NaN,NaN
12414,Wendell Smith Elementary School,sc148,"Robinson, Zulekha",tc1154,"McManus, Lisa",c104,Kindergarten,"Harris, Jayda A",st1833,PSF,...,NaN,NaN,NaN,NaN,56.0,NaN,NaN,47.0,NaN,65.0
12415,Wendell Smith Elementary School,sc148,"Robinson, Zulekha",tc1154,"McManus, Lisa",c104,Kindergarten,"Johnson, Kerrion",st1834,FSF,...,NaN,NaN,NaN,NaN,44.0,NaN,NaN,NaN,NaN,NaN
12416,Wendell Smith Elementary School,sc148,"Robinson, Zulekha",tc1154,"McManus, Lisa",c104,Kindergarten,"Johnson, Kerrion",st1834,NWF-CLS,...,NaN,NaN,NaN,NaN,19.0,NaN,NaN,NaN,NaN,NaN
12418,Wendell Smith Elementary School,sc148,"Robinson, Zulekha",tc1154,"McManus, Lisa",c104,Kindergarten,"Johnson, Kerrion",st1834,PSF,...,NaN,NaN,NaN,NaN,13.0,NaN,NaN,47.0,NaN,69.0
12419,Wendell Smith Elementary School,sc148,"Robinson, Zulekha",tc1154,"McManus, Lisa",c104,Kindergarten,"Adams, Semaj",st1837,FSF,...,NaN,NaN,NaN,NaN,39.0,NaN,NaN,NaN,NaN,NaN
12420,Wendell Smith Elementary School,sc148,"Robinson, Zulekha",tc1154,"McManus, Lisa",c104,Kindergarten,"Adams, Semaj",st1837,NWF-CLS,...,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN
12422,Wendell Smith Elementary School,sc148,"Robinson, Zulekha",tc1154,"McManus, Lisa",c104,Kindergarten,"Adams, Semaj",st1837,PSF,...,NaN,NaN,NaN,NaN,27.0,NaN,NaN,29.0,NaN,71.0
12423,Wendell Smith Elementary School,sc148,"Robinson, Zulekha",tc1154,"McManus, Lisa",c104,Kindergarten,"Jones, Dazyhre Shantell",st1839,FSF,...,NaN,NaN,NaN,NaN,31.0,NaN,NaN,NaN,NaN,NaN
12424,Wendell Smith Elementary School,sc148,"Robinson, Zulekha",tc1154,"McManus, Lisa",c104,Kindergarten,"Jones, Dazyhre Shantell",st1839,NWF-CLS,...,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN
12426,Wendell Smith Elementary School,sc148,"Robinson, Zulekha",tc1154,"McManus, Lisa",c104,Kindergarten,"Jones, Dazyhre Shantell",st1839,PSF,...,NaN,NaN,NaN,NaN,1.0,NaN,NaN,22.0,NaN,68.0
12427,Wendell Smith Elementary School,sc148,"Robinson, Zulekha",tc1154,"McManus, Lisa",c104,Kindergarten,"Smith, Jocelyn",st1933,PSF,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN

In [302]:
fy18eid=fy18e[['SchoolName','sch_id','TeacherName','tch_id','CoachName','coach_id','GradeLevel_FullName_18','Student','student_id']]

In [303]:
fsf=fy18e[fy18e['TestTypeCode']=='FSF']

In [304]:
fsf=fsf[['student_id','BOY','SEP','OCT','NOV','DEC','MOY']]

In [305]:
fsf[fsf.duplicated(['student_id'], keep=False)].sort_values(['student_id'])

      student_id   BOY  SEP   OCT  NOV  DEC   MOY
0         st0001   6.0  NaN   NaN  NaN  NaN   NaN
117       st0001   6.0  NaN   NaN  NaN  NaN   NaN
124       st0001   6.0  NaN   0.0  NaN  NaN  29.0
5         st0003  12.0  NaN   NaN  NaN  NaN   NaN
118       st0003  12.0  NaN   NaN  NaN  NaN  24.0
128       st0003  12.0  NaN   NaN  NaN  NaN  24.0
14        st0006   2.0  NaN   NaN  NaN  NaN   NaN
122       st0006   2.0  NaN   NaN  NaN  NaN   NaN
132       st0006   2.0  NaN   0.0  NaN  NaN  24.0
15        st0007   NaN  NaN   NaN  NaN  NaN  41.0
5250      st0007  18.0  NaN  20.0  NaN  NaN   NaN
51        st0016  19.0  NaN   NaN  NaN  NaN   NaN
123       st0016  19.0  NaN   NaN  NaN  NaN   NaN
136       st0016  19.0  NaN  21.0  NaN  NaN  34.0
12279     st0117   NaN  NaN   NaN  NaN  NaN  37.0
377       st0117  24.0  NaN  33.0  NaN  NaN   NaN
12283     st0120   NaN  NaN   NaN  NaN  NaN  45.0
384       st0120  24.0  NaN  50.0  NaN  NaN   NaN
385       st0121   7.0  NaN  30.0  NaN  NaN   NaN
12287     st0121   NaN  NaN   NaN  NaN  NaN  38.0
392       st0124   2.0  NaN  19.0  NaN  NaN   NaN
12291     st0124   NaN  NaN   NaN  NaN  NaN  37.0
396       st0126   0.0  NaN  24.0  NaN  NaN   NaN
12295     st0126   NaN  NaN   NaN  NaN  NaN   8.0
397       st0127  13.0  NaN  36.0  NaN  NaN   NaN
12299     st0127   NaN  NaN   NaN  NaN  NaN   NaN
398       st0128  20.0  NaN  31.0  NaN  NaN   NaN
12303     st0128   NaN  NaN   NaN  NaN  NaN  39.0
12307     st0131   NaN  NaN   NaN  NaN  NaN   2.0
405       st0131   0.0  NaN  21.0  NaN  NaN   NaN
...          ...   ...  ...   ...  ...  ...   ...
11468     st1815   7.0  NaN  20.0  NaN  NaN  30.0
12379     st1815   NaN  NaN   NaN  NaN  NaN  30.0
12383     st1817   NaN  NaN   NaN  NaN  NaN  58.0
11476     st1817  24.0  NaN  51.0  NaN  NaN  58.0
12387     st1818   NaN  NaN   NaN  NaN  NaN  48.0
11480     st1818  32.0  NaN  48.0  NaN  NaN  48.0
12391     st1820   NaN  NaN   NaN  NaN  NaN  24.0
11488     st1820   8.0  NaN  17.0  NaN  NaN  24.0
11502     st1824   4.0  NaN   7.0  NaN  NaN  31.0
12395     st1824   NaN  NaN   NaN  NaN  NaN  31.0
11674     st1826   8.0  NaN   0.0  NaN  NaN   NaN
11510     st1826   NaN  NaN   NaN  NaN  NaN  41.0
12403     st1826   NaN  NaN   NaN  NaN  NaN  41.0
11526     st1830  16.0  NaN  28.0  NaN  NaN  51.0
12407     st1830   NaN  NaN   NaN  NaN  NaN  51.0
11538     st1833   0.0  NaN  10.0  NaN  NaN  46.0
12411     st1833   NaN  NaN   NaN  NaN  NaN  46.0
11542     st1834   2.0  NaN  10.0  NaN  NaN  44.0
12415     st1834   NaN  NaN   NaN  NaN  NaN  44.0
11551     st1837   NaN  NaN   NaN  NaN  NaN  39.0
12419     st1837   NaN  NaN   NaN  NaN  NaN  39.0
11675     st1837  20.0  NaN  40.0  NaN  NaN   NaN
11555     st1838   NaN  NaN   NaN  NaN  NaN  18.0
11676     st1838  19.0  NaN  18.0  NaN  NaN   NaN
12423     st1839   NaN  NaN   NaN  NaN  NaN  31.0
11559     st1839   NaN  NaN   NaN  NaN  NaN  31.0
11670     st1840  14.0  NaN  32.0  NaN  NaN  53.0
12399     st1840   NaN  NaN   NaN  NaN  NaN  53.0
11753     st1852  14.0  NaN   NaN  NaN  NaN  29.0
11721     st1852  14.0  NaN   NaN  NaN  NaN  29.0

[112 rows x 7 columns]

In [161]:
#d = fsf.groupby('student_id')[['BOY','SEP','OCT','NOV','DEC','MOY']].apply(lambda g: g.values.tolist()).to_dict()

In [135]:
#fsf.sort_values(['student_id'], inplace=True)

In [306]:
fsf['MOY']=fsf.groupby(['student_id'], sort=False)['MOY'].apply(lambda x: x.bfill())

In [307]:
fsf['DEC']=fsf.groupby(['student_id'], sort=False)['DEC'].apply(lambda x: x.bfill())

In [308]:
fsf['NOV']=fsf.groupby(['student_id'], sort=False)['NOV'].apply(lambda x: x.bfill())

In [309]:
fsf['OCT']=fsf.groupby(['student_id'], sort=False)['OCT'].apply(lambda x: x.bfill())

In [310]:
fsf['SEP']=fsf.groupby(['student_id'], sort=False)['SEP'].apply(lambda x: x.bfill())

In [311]:
fsf['BOY']=fsf.groupby(['student_id'], sort=False)['BOY'].apply(lambda x: x.bfill())

In [312]:
fsf[fsf.duplicated(['student_id'], keep=False)].sort_values(['student_id'])

      student_id   BOY  SEP   OCT  NOV  DEC   MOY
0         st0001   6.0  NaN   0.0  NaN  NaN  29.0
117       st0001   6.0  NaN   0.0  NaN  NaN  29.0
124       st0001   6.0  NaN   0.0  NaN  NaN  29.0
5         st0003  12.0  NaN   NaN  NaN  NaN  24.0
118       st0003  12.0  NaN   NaN  NaN  NaN  24.0
128       st0003  12.0  NaN   NaN  NaN  NaN  24.0
14        st0006   2.0  NaN   0.0  NaN  NaN  24.0
122       st0006   2.0  NaN   0.0  NaN  NaN  24.0
132       st0006   2.0  NaN   0.0  NaN  NaN  24.0
15        st0007  18.0  NaN  20.0  NaN  NaN  41.0
5250      st0007  18.0  NaN  20.0  NaN  NaN   NaN
51        st0016  19.0  NaN  21.0  NaN  NaN  34.0
123       st0016  19.0  NaN  21.0  NaN  NaN  34.0
136       st0016  19.0  NaN  21.0  NaN  NaN  34.0
12279     st0117   NaN  NaN   NaN  NaN  NaN  37.0
377       st0117  24.0  NaN  33.0  NaN  NaN  37.0
12283     st0120   NaN  NaN   NaN  NaN  NaN  45.0
384       st0120  24.0  NaN  50.0  NaN  NaN  45.0
385       st0121   7.0  NaN  30.0  NaN  NaN  38.0
12287     st0121   NaN  NaN   NaN  NaN  NaN  38.0
392       st0124   2.0  NaN  19.0  NaN  NaN  37.0
12291     st0124   NaN  NaN   NaN  NaN  NaN  37.0
396       st0126   0.0  NaN  24.0  NaN  NaN   8.0
12295     st0126   NaN  NaN   NaN  NaN  NaN   8.0
397       st0127  13.0  NaN  36.0  NaN  NaN   NaN
12299     st0127   NaN  NaN   NaN  NaN  NaN   NaN
398       st0128  20.0  NaN  31.0  NaN  NaN  39.0
12303     st0128   NaN  NaN   NaN  NaN  NaN  39.0
12307     st0131   NaN  NaN   NaN  NaN  NaN   2.0
405       st0131   0.0  NaN  21.0  NaN  NaN   2.0
...          ...   ...  ...   ...  ...  ...   ...
11468     st1815   7.0  NaN  20.0  NaN  NaN  30.0
12379     st1815   NaN  NaN   NaN  NaN  NaN  30.0
12383     st1817   NaN  NaN   NaN  NaN  NaN  58.0
11476     st1817  24.0  NaN  51.0  NaN  NaN  58.0
12387     st1818   NaN  NaN   NaN  NaN  NaN  48.0
11480     st1818  32.0  NaN  48.0  NaN  NaN  48.0
12391     st1820   NaN  NaN   NaN  NaN  NaN  24.0
11488     st1820   8.0  NaN  17.0  NaN  NaN  24.0
11502     st1824   4.0  NaN   7.0  NaN  NaN  31.0
12395     st1824   NaN  NaN   NaN  NaN  NaN  31.0
11674     st1826   8.0  NaN   0.0  NaN  NaN  41.0
11510     st1826   8.0  NaN   0.0  NaN  NaN  41.0
12403     st1826   NaN  NaN   NaN  NaN  NaN  41.0
11526     st1830  16.0  NaN  28.0  NaN  NaN  51.0
12407     st1830   NaN  NaN   NaN  NaN  NaN  51.0
11538     st1833   0.0  NaN  10.0  NaN  NaN  46.0
12411     st1833   NaN  NaN   NaN  NaN  NaN  46.0
11542     st1834   2.0  NaN  10.0  NaN  NaN  44.0
12415     st1834   NaN  NaN   NaN  NaN  NaN  44.0
11551     st1837  20.0  NaN  40.0  NaN  NaN  39.0
12419     st1837   NaN  NaN   NaN  NaN  NaN  39.0
11675     st1837  20.0  NaN  40.0  NaN  NaN  39.0
11555     st1838  19.0  NaN  18.0  NaN  NaN  18.0
11676     st1838  19.0  NaN  18.0  NaN  NaN   NaN
12423     st1839   NaN  NaN   NaN  NaN  NaN  31.0
11559     st1839   NaN  NaN   NaN  NaN  NaN  31.0
11670     st1840  14.0  NaN  32.0  NaN  NaN  53.0
12399     st1840   NaN  NaN   NaN  NaN  NaN  53.0
11753     st1852  14.0  NaN   NaN  NaN  NaN  29.0
11721     st1852  14.0  NaN   NaN  NaN  NaN  29.0

[112 rows x 7 columns]

In [313]:
fsf.drop_duplicates(subset=['student_id'],keep='first', inplace=True)

In [314]:
fsf.rename({'MOY':'MOY_FSF'},axis='columns' ,inplace=True)

In [315]:
fsf['fpm_fsf']=fsf['OCT']
fsf['fpm_fsf']=np.where((pd.isnull(fsf.fpm_fsf))&(fsf['NOV']!=np.NaN),fsf['NOV'],fsf['fpm_fsf'])
fsf['fpm_fsf']=np.where((pd.isnull(fsf.fpm_fsf))&(fsf['DEC']!=np.NaN),fsf['NOV'],fsf['fpm_fsf'])
fsf['fpm_fsf']=np.where((pd.isnull(fsf.fpm_fsf))&(fsf['SEP']!=np.NaN),fsf['NOV'],fsf['fpm_fsf'])

In [316]:
fsf.drop(['SEP','OCT','NOV','DEC'], axis=1, inplace=True)

In [317]:
nwf=fy18e[fy18e['TestTypeCode']=='NWF-CLS']

In [318]:
nwf=nwf[['student_id','MOY','JAN','FEB','Mar','APR','EOY']]

In [319]:
nwf[nwf.duplicated(['student_id'], keep=False)].sort_values(['student_id'])

      student_id   MOY  JAN  FEB   Mar  APR   EOY
119       st0003  21.0  NaN  NaN   NaN  NaN  39.0
129       st0003  21.0  NaN  NaN   NaN  NaN  39.0
2167      st0461  24.0  NaN  NaN  21.0  NaN  27.0
4074      st0461  24.0  NaN  NaN   NaN  NaN   NaN
3207      st0575  36.0  NaN  NaN   NaN  NaN  44.0
3219      st0575  36.0  NaN  NaN   NaN  NaN   NaN
4498      st0743  38.0  NaN  NaN   NaN  NaN  47.0
4543      st0743  38.0  NaN  NaN   NaN  NaN  47.0
4502      st0744   5.0  NaN  NaN   NaN  NaN  12.0
4547      st0744   5.0  NaN  NaN   NaN  NaN  12.0
12348     st1798  20.0  NaN  NaN   NaN  NaN   NaN
11404     st1798  20.0  NaN  NaN   NaN  NaN   NaN
11408     st1799  11.0  NaN  NaN   NaN  NaN   NaN
12352     st1799  11.0  NaN  NaN   NaN  NaN   NaN
12356     st1801  12.0  NaN  NaN   NaN  NaN   NaN
11416     st1801  12.0  NaN  NaN   NaN  NaN   NaN
11428     st1804  22.0  NaN  NaN   NaN  NaN   NaN
12360     st1804  22.0  NaN  NaN   NaN  NaN   NaN
11445     st1809   0.0  NaN  NaN   NaN  NaN   NaN
12364     st1809   0.0  NaN  NaN   NaN  NaN   NaN
11453     st1811   0.0  NaN  NaN   NaN  NaN   NaN
12368     st1811   0.0  NaN  NaN   NaN  NaN   NaN
11461     st1813  64.0  NaN  NaN   NaN  NaN   NaN
12372     st1813  64.0  NaN  NaN   NaN  NaN   NaN
11465     st1814  27.0  NaN  NaN   NaN  NaN   NaN
12376     st1814  27.0  NaN  NaN   NaN  NaN   NaN
12380     st1815  15.0  NaN  NaN   NaN  NaN   NaN
11469     st1815  15.0  NaN  NaN   NaN  NaN   NaN
12384     st1817  62.0  NaN  NaN   NaN  NaN   NaN
11477     st1817  62.0  NaN  NaN   NaN  NaN   NaN
12388     st1818   9.0  NaN  NaN   NaN  NaN   NaN
11481     st1818   9.0  NaN  NaN   NaN  NaN   NaN
12392     st1820   0.0  NaN  NaN   NaN  NaN   NaN
11489     st1820   0.0  NaN  NaN   NaN  NaN   NaN
12396     st1824  17.0  NaN  NaN   NaN  NaN   NaN
11503     st1824  17.0  NaN  NaN   NaN  NaN   NaN
12404     st1826  16.0  NaN  NaN   NaN  NaN   NaN
11511     st1826  16.0  NaN  NaN   NaN  NaN   NaN
11527     st1830  14.0  NaN  NaN   NaN  NaN   NaN
12408     st1830  14.0  NaN  NaN   NaN  NaN   NaN
12412     st1833  24.0  NaN  NaN   NaN  NaN   NaN
11539     st1833  24.0  NaN  NaN   NaN  NaN   NaN
11543     st1834  19.0  NaN  NaN   NaN  NaN   NaN
12416     st1834  19.0  NaN  NaN   NaN  NaN   NaN
11552     st1837   0.0  NaN  NaN   NaN  NaN   NaN
12420     st1837   0.0  NaN  NaN   NaN  NaN   NaN
11560     st1839   0.0  NaN  NaN   NaN  NaN   NaN
12424     st1839   0.0  NaN  NaN   NaN  NaN   NaN
11671     st1840  13.0  NaN  NaN   NaN  NaN   NaN
12400     st1840  13.0  NaN  NaN   NaN  NaN   NaN
11722     st1852   7.0  NaN  NaN   NaN  NaN   NaN
11754     st1852   7.0  NaN  NaN   7.0  NaN  23.0

In [320]:
nwf['MOY']=nwf.groupby(['student_id'], sort=False)['MOY'].apply(lambda x: x.bfill())

In [321]:
nwf['JAN']=nwf.groupby(['student_id'], sort=False)['JAN'].apply(lambda x: x.bfill())

In [322]:
nwf['FEB']=nwf.groupby(['student_id'], sort=False)['FEB'].apply(lambda x: x.bfill())

In [323]:
nwf['Mar']=nwf.groupby(['student_id'], sort=False)['Mar'].apply(lambda x: x.bfill())

In [324]:
nwf['APR']=nwf.groupby(['student_id'], sort=False)['APR'].apply(lambda x: x.bfill())

In [325]:
nwf['EOY']=nwf.groupby(['student_id'], sort=False)['EOY'].apply(lambda x: x.bfill())

In [326]:
nwf.drop_duplicates(subset=['student_id'],keep='first', inplace=True)

In [327]:
nwf.rename({'MOY':'MOY_NWF','EOY':'EOY_NWF'},axis='columns' ,inplace=True)

In [328]:
nwf['spm_nwf']=nwf['Mar']
nwf['spm_nwf']=np.where((pd.isnull(nwf.spm_nwf))&(nwf['APR']!=np.NaN),nwf['APR'],nwf['spm_nwf'])
nwf['spm_nwf']=np.where((pd.isnull(nwf.spm_nwf))&(nwf['JAN']!=np.NaN),nwf['APR'],nwf['spm_nwf'])
nwf['spm_nwf']=np.where((pd.isnull(nwf.spm_nwf))&(nwf['FEB']!=np.NaN),nwf['APR'],nwf['spm_nwf'])

In [329]:
nwf.drop(['JAN','FEB','Mar','APR'], axis=1, inplace=True)

In [295]:
nwf

,SchoolName,sch_id,TeacherName,tch_id,CoachName,coach_id,GradeLevel_FullName_18,Student,student_id,MOY_NWF,EOY_NWF,spm_nwf
2,Shoesmith,sc142,"Hobson, Ashley",tc1074,"Randruut, Avo",c106,Kindergarten,"Howard, Jamayle Christopher",st0002,19.0,51.0,NaN
7,Shoesmith,sc142,"Hobson, Ashley",tc1074,"Randruut, Avo",c106,Kindergarten,"Peters, Kameron Demil",st0004,27.0,43.0,NaN
11,Shoesmith,sc142,"Hobson, Ashley",tc1074,"Randruut, Avo",c106,Kindergarten,"Hamilton, Madison Brielle",st0005,25.0,36.0,NaN
16,Shoesmith,sc142,"Hobson, Ashley",tc1074,"Randruut, Avo",c106,Kindergarten,"Coles, Journie",st0007,44.0,55.0,NaN
20,Shoesmith,sc142,"Hobson, Ashley",tc1074,"Randruut, Avo",c106,Kindergarten,"Marshall, Mason",st0008,32.0,45.0,NaN
24,Shoesmith,sc142,"Hobson, Ashley",tc1074,"Randruut, Avo",c106,Kindergarten,"KYEI, NASIR",st0009,1.0,33.0,NaN
28,Shoesmith,sc142,"Hobson, Ashley",tc1074,"Randruut, Avo",c106,Kindergarten,"Webb-Arrieta, Kyrie B",st0010,33.0,63.0,NaN
32,Shoesmith,sc142,"Hobson, Ashley",tc1074,"Randruut, Avo",c106,Kindergarten,"Harper, Anthony J",st0011,41.0,47.0,NaN
36,Shoesmith,sc142,"Hobson, Ashley",tc1074,"Randruut, Avo",c106,Kindergarten,"Hethington, Leelah Riyan",st0012,29.0,39.0,NaN
40,Shoesmith,sc142,"Hobson, Ashley",tc1074,"Randruut, Avo",c106,Kindergarten,"Burbon, Amari Emiliano",st0013,40.0,55.0,NaN
44,Shoesmith,sc142,"Hobson, Ashley",tc1074,"Randruut, Avo",c106,Kindergarten,"Hood, Nyla Regina",st0014,31.0,88.0,NaN
48,Shoesmith,sc142,"Hobson, Ashley",tc1074,"Randruut, Avo",c106,Kindergarten,"Bruce, Latasha",st0015,27.0,39.0,NaN
53,Shoesmith,sc142,"Hobson, Ashley",tc1074,"Randruut, Avo",c106,Kindergarten,"Spencer, Akira Haylee",st0017,34.0,50.0,NaN
58,Shoesmith,sc142,"Hobson, Ashley",tc1074,"Randruut, Avo",c106,Kindergarten,"Wilson, Kinsley",st0019,28.0,45.0,NaN
62,Shoesmith,sc142,"Hobson, Ashley",tc1074,"Randruut, Avo",c106,Kindergarten,"Burkett, Jaray",st0020,29.0,39.0,NaN
66,Shoesmith,sc142,"Hobson, Ashley",tc1074,"Randruut, Avo",c106,Kindergarten,"Williams, Vina-Marie",st0021,27.0,34.0,NaN
70,Shoesmith,sc142,"Hobson, Ashley",tc1074,"Randruut, Avo",c106,Kindergarten,"Curry II, Terrill YC",st0022,24.0,28.0,NaN
74,Shoesmith,sc142,"Hobson, Ashley",tc1074,"Randruut, Avo",c106,Kindergarten,"Hamilton, Baisedon",st0023,27.0,NaN,NaN
78,Shoesmith,sc142,"Hobson, Ashley",tc1074,"Randruut, Avo",c106,Kindergarten,"London, Omari Malone",st0024,22.0,56.0,NaN
82,Shoesmith,sc142,"Hobson, Ashley",tc1074,"Randruut, Avo",c106,Kindergarten,"Love-Sanders, Joy",st0025,24.0,44.0,NaN
86,Shoesmith,sc142,"Hobson, Ashley",tc1074,"Randruut, Avo",c106,Kindergarten,"Miller, Essiah Love",st0026,58.0,141.0,NaN
90,Shoesmith,sc142,"Hobson, Ashley",tc1074,"Randruut, Avo",c106,Kindergarten,"Enoch, Desiree Marie",st0027,23.0,34.0,NaN
94,Shoesmith,sc142,"Hobson, Ashley",tc1074,"Randruut, Avo",c106,Kindergarten,"Garcia, Jorge Alberto",st0028,0.0,13.0,NaN
98,Shoesmith,sc142,"Hobson, Ashley",tc1074,"Randruut, Avo",c106,Kindergarten,"Johnson, Jason Lamont",st0029,21.0,28.0,NaN
102,Shoesmith,sc142,"Hobson, Ashley",tc1074,"Randruut, Avo",c106,Kindergarten,"Reese, Nasir Rakim",st0030,23.0,40.0,NaN
106,Shoesmith,sc142,"Hobson, Ashley",tc1074,"Randruut, Avo",c106,Kindergarten,"Charles, Natalia Bria Janae",st0031,38.0,27.0,NaN
110,Shoesmith,sc142,"Hobson, Ashley",tc1074,"Randruut, Avo",c106,Kindergarten,"Hughes, Madison Mckenzie",st0032,29.0,55.0,NaN
114,Shoesmith,sc142,"Hobson, Ashley",tc1074,"Randruut, Avo",c106,Kindergarten,"Ahmed, Minahil Aminiyah",st0033,40.0,42.0,NaN
119,Shoesmith,sc142,"Hobson, Ashley",tc1074,"Randruut, Avo",c106,Kindergarten,"Douse, A'Niyah Marie",st0003,21.0,39.0,NaN
125,Shoesmith,sc142,"Hobson, Ashley",tc1074,"Randruut, Avo",c106,Kindergarten,"Buchanan, Ma'kayla Eternity",st0001,0.0,11.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
12228,Mahalia Jackson Elementary School,sc130,"Jimenez, Adam",tc1082,"Lepeley, Karina",c103,Kindergarten,"Brumfield, Damyra",st1920,31.0,42.0,NaN
12232,Mahalia Jackson Elementary School,sc130,"Jimenez, Adam",tc1082,"Lepeley, Karina",c103,Kindergarten,"Brown, Marco Josiah",st1921,NaN,54.0,NaN
12236,Mahalia Jackson Elementary School,sc130,"Jimenez, Adam",tc1082,"Lepeley, Karina",c103,Kindergarten,"McCline, Darmoine",st1922,0.0,11.0,NaN
12240,Mahalia Jackson Elementary School,sc130,"Jimenez, Adam",tc1082,"Lepeley, Karina",c103,Kindergarten,"Patton, Kay'Leigh",st1923,28.0,41.0,NaN
12244,Mahalia Jackson Elementary School,sc130,"Jimenez, Adam",tc1082,"Lepeley, Karina",c103,Kindergarten,"King, Lovely",st1924,2.0,10.0,NaN
12248,Mahalia Jackson Elementary School,sc130,"Jimenez, Adam",tc1082,"Lepeley, Karina",c103,Kindergarten,"Russell, Diamond Nicole",st1925,27.0,43.0,NaN
12252,Mahalia Jackson Elementary School,sc130,"Jimenez, Adam",tc1082,"Lepeley, Karina",c103,Kindergarten,"Woods, Demi",st1926,24.0,46.0,NaN
12256,Mahalia Jackson Elementary School,sc130,"Jimenez, Adam",tc1082,"Lepeley, Karina",c103,Kindergarten,"Sampson, Jordan",st1927,0.0,12.0,NaN
12260,Mahalia Jackson Elementary School,sc130,"Jimenez, Adam",tc1082,"Lepeley, Karina",c103,Kindergarten,"Harbin, Ki'Mani",st1928,2.0,NaN,NaN
12264,Mahalia Jackson Elementary School,sc130,"Jimenez, Adam",tc1082,"Lepeley, Karina",c103,Kindergarten,"Pickett, Dynastie",st1929,31.0,45.0,NaN
12268,Mahalia Jackson Elementary School,sc130,"Jimenez, Adam",tc1082,"Lepeley, Karina",c103,Kindergarten,"Latiker, Victor",st1930,30.0,56.0,NaN
12272,Mahalia Jackson Elementary School,sc130,"Jimenez, Adam",tc1082,"Lepeley, Karina",c103,Kindergarten,"Washington, Morgan Evette",st1931,14.0,31.0,NaN
12276,Mahalia Jackson Elementary School,sc130,"Jimenez, Adam",tc1082,"Lepeley, Karina",c103,Kindergarten,"Chapman, Dominique",st1932,1.0,11.0,NaN
12280,Rachel Carson Elementary,sc141,"Minton, Meghan",tc1117,"Randruut, Avo",c106,Kindergarten,"Byrd, Keyshawn Deon",st0117,22.0,32.0,NaN
12284,Rachel Carson Elementary,sc141,"Minton, Meghan",tc1117,"Randruut, Avo",c106,Kindergarten,"Rodriguez, Mia",st0120,25.0,47.0,NaN
12288,Rachel Carson Elementary,sc141,"Minton, Meghan",tc1117,"Randruut, Avo",c106,Kindergarten,"Lara, Aleanni",st0121,24.0,38.0,NaN
12292,Rachel Carson Elementary,sc141,"Minton, Meghan",tc1117,"Randruut, Avo",c106,Kindergarten,"Washington, Jayden Jeremiah",st0124,18.0,22.0,NaN
12296,Rachel Carson Elementary,sc141,"Minton, Meghan",tc1117,"Randruut, Avo",c106,Kindergarten,"Trujillo, Jaelyn",st0126,4.0,4.0,NaN
12300,Rachel Carson Elementary,sc141,"Minton, Meghan",tc1117,"Randruut, Avo",c106,Kindergarten,"Cruz, Arimaoniy Napoleeon",st0127,NaN,27.0,NaN
12304,Rachel Carson Elementary,sc141,"Minton, Meghan",tc1117,"Randruut, Avo",c106,Kindergarten,"Vargas, Neftali Jesus",st0128,17.0,45.0,NaN
12308,Rachel Carson Elementary,sc141,"Minton, Meghan",tc1117,"Randruut, Avo",c106,Kindergarten,"Mazari, Leah Juliana",st0131,7.0,8.0,NaN
12312,Rachel Carson Elementary,sc141,"Minton, Meghan",tc1117,"Randruut, Avo",c106,Kindergarten,"Nevarez, Luis Epifanio",st0134,30.0,32.0,NaN
12316,Rachel Carson Elementary,sc141,"Minton, Meghan",tc1117,"Randruut, Avo",c106,Kindergarten,"Batrez, Adalynn",st0136,12.0,29.0,NaN
12320,Rachel Carson Elementary,sc141,"Minton, Meghan",tc1117,"Randruut, Avo",c106,Kindergarten,"Alvarado, Robin Elizabeth",st0140,28.0,36.0,NaN
12324,Rachel Carson Elementary,sc141,"Minton, Meghan",tc1117,"Randruut, Avo",c106,Kindergarten,"Sanchez, Christopher Allen",st0142,31.0,57.0,NaN
12328,Rachel Carson Elementary,sc141,"Minton, Meghan",tc1117,"Randruut, Avo",c106,Kindergarten,"Rogers, Kaiden J",st0143,41.0,91.0,NaN
12332,Rachel Carson Elementary,sc141,"Minton, Meghan",tc1117,"Randruut, Avo",c106,Kindergarten,"Wages, Mitchell",st0145,9.0,27.0,NaN
12336,Rachel Carson Elementary,sc141,"Minton, Meghan",tc1117,"Randruut, Avo",c106,Kindergarten,"Zamudio, Marily",st0246,12.0,18.0,NaN
12340,Rachel Carson Elementary,sc141,"Minton, Meghan",tc1117,"Randruut, Avo",c106,Kindergarten,"Biurquis, Leonardo David",st0152,7.0,12.0,NaN
12344,Rachel Carson Elementary,sc141,"Minton, Meghan",tc1117,"Randruut, Avo",c106,Kindergarten,"Cheeks, Tylen Cyntrell",st0153,NaN,NaN,NaN

In [258]:
psf=fy18e[fy18e['TestTypeCode']=='PSF']

In [259]:
psf=psf[['student_id','MOY','JAN','FEB','Mar','APR','EOY']]
psf

      student_id   MOY  JAN  FEB   Mar  APR   EOY
4         st0002  56.0  NaN  NaN  67.0  NaN  61.0
9         st0004  62.0  NaN  NaN  71.0  NaN  63.0
13        st0005  51.0  NaN  NaN  67.0  NaN  60.0
18        st0007  17.0  NaN  NaN  14.0  NaN  69.0
22        st0008  55.0  NaN  NaN  51.0  NaN  58.0
26        st0009  19.0  NaN  NaN  15.0  NaN  19.0
30        st0010  14.0  NaN  NaN  25.0  NaN  65.0
34        st0011  29.0  NaN  NaN  70.0  NaN  60.0
38        st0012  16.0  NaN  NaN  61.0  NaN  71.0
42        st0013  48.0  NaN  NaN  71.0  NaN  60.0
46        st0014  53.0  NaN  NaN  66.0  NaN  66.0
50        st0015  17.0  NaN  NaN  52.0  NaN  65.0
55        st0017  44.0  NaN  NaN  71.0  NaN  55.0
60        st0019  63.0  NaN  NaN  70.0  NaN  71.0
64        st0020  17.0  NaN  NaN  21.0  NaN  56.0
68        st0021  38.0  NaN  NaN  42.0  NaN  62.0
72        st0022  36.0  NaN  NaN  44.0  NaN  60.0
76        st0023  42.0  NaN  NaN   NaN  NaN   NaN
80        st0024  48.0  NaN  NaN  55.0  NaN  61.0
84        st0025  35.0  NaN  NaN  63.0  NaN  66.0
88        st0026  56.0  NaN  NaN  65.0  NaN  58.0
92        st0027  40.0  NaN  NaN  61.0  NaN  58.0
96        st0028  16.0  NaN  NaN  34.0  NaN  61.0
100       st0029  19.0  NaN  NaN  52.0  NaN  56.0
104       st0030  49.0  NaN  NaN  65.0  NaN  71.0
108       st0031  16.0  NaN  NaN  24.0  NaN  56.0
112       st0032  61.0  NaN  NaN  72.0  NaN  59.0
116       st0033  17.0  NaN  NaN  32.0  NaN  54.0
121       st0003   4.0  NaN  NaN  20.0  NaN  66.0
127       st0001  17.0  NaN  NaN  11.0  NaN  56.0
...          ...   ...  ...  ...   ...  ...   ...
12314     st0134  52.0  NaN  NaN  66.0  NaN  66.0
12318     st0136  19.0  NaN  NaN  41.0  NaN  53.0
12322     st0140  29.0  NaN  NaN  52.0  NaN  61.0
12326     st0142  24.0  NaN  NaN  59.0  NaN  62.0
12330     st0143  48.0  NaN  NaN  64.0  NaN  60.0
12334     st0145  14.0  NaN  NaN  13.0  NaN  46.0
12338     st0246  18.0  NaN  NaN  25.0  NaN  33.0
12342     st0152  10.0  NaN  NaN  16.0  NaN  33.0
12346     st0153   NaN  NaN  NaN   NaN  NaN   NaN
12350     st1798  31.0  NaN  NaN  54.0  NaN  61.0
12354     st1799  16.0  NaN  NaN  37.0  NaN  68.0
12358     st1801  17.0  NaN  NaN  46.0  NaN  53.0
12362     st1804  71.0  NaN  NaN  70.0  NaN  62.0
12366     st1809  53.0  NaN  NaN  31.0  NaN  50.0
12370     st1811   1.0  NaN  NaN  32.0  NaN  58.0
12374     st1813  44.0  NaN  NaN  46.0  NaN  58.0
12378     st1814  71.0  NaN  NaN  67.0  NaN  57.0
12382     st1815  14.0  NaN  NaN  17.0  NaN  69.0
12386     st1817  23.0  NaN  NaN  65.0  NaN  50.0
12390     st1818  36.0  NaN  NaN  61.0  NaN  72.0
12394     st1820   1.0  NaN  NaN  23.0  NaN  60.0
12398     st1824  11.0  NaN  NaN  55.0  NaN  62.0
12402     st1840  25.0  NaN  NaN  41.0  NaN  53.0
12406     st1826  52.0  NaN  NaN  70.0  NaN  50.0
12410     st1830   8.0  NaN  NaN   NaN  NaN   NaN
12414     st1833  56.0  NaN  NaN  47.0  NaN  65.0
12418     st1834  13.0  NaN  NaN  47.0  NaN  69.0
12422     st1837  27.0  NaN  NaN  29.0  NaN  71.0
12426     st1839   1.0  NaN  NaN  22.0  NaN  68.0
12427     st1933   NaN  NaN  NaN   3.0  NaN   NaN

[1385 rows x 7 columns]

In [260]:
psf['MOY']=psf.groupby(['student_id'], sort=False)['MOY'].apply(lambda x: x.bfill())

In [261]:
psf['JAN']=psf.groupby(['student_id'], sort=False)['JAN'].apply(lambda x: x.bfill())

In [262]:
psf['FEB']=psf.groupby(['student_id'], sort=False)['FEB'].apply(lambda x: x.bfill())

In [263]:
psf['Mar']=psf.groupby(['student_id'], sort=False)['Mar'].apply(lambda x: x.bfill())

In [264]:
psf['APR']=psf.groupby(['student_id'], sort=False)['APR'].apply(lambda x: x.bfill())

In [265]:
psf['EOY']=psf.groupby(['student_id'], sort=False)['EOY'].apply(lambda x: x.bfill())

In [266]:
psf[psf.duplicated(['student_id'], keep=False)].sort_values(['student_id'])

      student_id   MOY  JAN  FEB   Mar  APR   EOY
121       st0003   4.0  NaN  NaN  20.0  NaN  66.0
131       st0003   4.0  NaN  NaN  20.0  NaN  66.0
2169      st0461  12.0  NaN  NaN  12.0  NaN  27.0
4076      st0461  12.0  NaN  NaN   NaN  NaN   NaN
3209      st0575  48.0  NaN  NaN  69.0  NaN  68.0
3221      st0575  48.0  NaN  NaN  69.0  NaN   NaN
4500      st0743  13.0  NaN  NaN  57.0  NaN  76.0
4545      st0743  13.0  NaN  NaN   NaN  NaN  76.0
4504      st0744  29.0  NaN  NaN  32.0  NaN  17.0
4549      st0744  29.0  NaN  NaN   NaN  NaN  17.0
12350     st1798  31.0  NaN  NaN  54.0  NaN  61.0
11406     st1798  31.0  NaN  NaN  54.0  NaN  61.0
11410     st1799  16.0  NaN  NaN  37.0  NaN  68.0
12354     st1799  16.0  NaN  NaN  37.0  NaN  68.0
12358     st1801  17.0  NaN  NaN  46.0  NaN  53.0
11418     st1801  17.0  NaN  NaN  46.0  NaN  53.0
11430     st1804  71.0  NaN  NaN  70.0  NaN  62.0
12362     st1804  71.0  NaN  NaN  70.0  NaN  62.0
11447     st1809  53.0  NaN  NaN  31.0  NaN  50.0
12366     st1809  53.0  NaN  NaN  31.0  NaN  50.0
11455     st1811   1.0  NaN  NaN  32.0  NaN  58.0
12370     st1811   1.0  NaN  NaN  32.0  NaN  58.0
11463     st1813  44.0  NaN  NaN  46.0  NaN  58.0
12374     st1813  44.0  NaN  NaN  46.0  NaN  58.0
11467     st1814  71.0  NaN  NaN  67.0  NaN  57.0
12378     st1814  71.0  NaN  NaN  67.0  NaN  57.0
12382     st1815  14.0  NaN  NaN  17.0  NaN  69.0
11471     st1815  14.0  NaN  NaN  17.0  NaN  69.0
12386     st1817  23.0  NaN  NaN  65.0  NaN  50.0
11479     st1817  23.0  NaN  NaN  65.0  NaN  50.0
12390     st1818  36.0  NaN  NaN  61.0  NaN  72.0
11483     st1818  36.0  NaN  NaN  61.0  NaN  72.0
12394     st1820   1.0  NaN  NaN  23.0  NaN  60.0
11491     st1820   1.0  NaN  NaN  23.0  NaN  60.0
12398     st1824  11.0  NaN  NaN  55.0  NaN  62.0
11505     st1824  11.0  NaN  NaN  55.0  NaN  62.0
12406     st1826  52.0  NaN  NaN  70.0  NaN  50.0
11513     st1826  52.0  NaN  NaN  70.0  NaN  50.0
11529     st1830   8.0  NaN  NaN   NaN  NaN   NaN
12410     st1830   8.0  NaN  NaN   NaN  NaN   NaN
12414     st1833  56.0  NaN  NaN  47.0  NaN  65.0
11541     st1833  56.0  NaN  NaN  47.0  NaN  65.0
11545     st1834  13.0  NaN  NaN  47.0  NaN  69.0
12418     st1834  13.0  NaN  NaN  47.0  NaN  69.0
11554     st1837  27.0  NaN  NaN  29.0  NaN  71.0
12422     st1837  27.0  NaN  NaN  29.0  NaN  71.0
11562     st1839   1.0  NaN  NaN  22.0  NaN  68.0
12426     st1839   1.0  NaN  NaN  22.0  NaN  68.0
11673     st1840  25.0  NaN  NaN  41.0  NaN  53.0
12402     st1840  25.0  NaN  NaN  41.0  NaN  53.0
11724     st1852  26.0  NaN  NaN  32.0  NaN  47.0
11756     st1852  26.0  NaN  NaN  32.0  NaN  47.0

In [268]:
psf['student_id'].nunique()

1359

In [269]:
psf.drop_duplicates(subset=['student_id'],keep='first', inplace=True)

In [270]:
psf.rename({'MOY':'MOY_PSF','EOY':'EOY_PSF'},axis='columns' ,inplace=True)

In [271]:
psf['spm_psf']=psf['Mar']
psf['spm_psf']=np.where((pd.isnull(psf.spm_psf))&(psf['APR']!=np.NaN),psf['APR'],psf['spm_psf'])
psf['spm_psf']=np.where((pd.isnull(psf.spm_psf))&(psf['FEB']!=np.NaN),psf['FEB'],psf['spm_psf'])
psf['spm_psf']=np.where((pd.isnull(psf.spm_psf))&(psf['JAN']!=np.NaN),psf['JAN'],psf['spm_psf'])

In [272]:
psf.drop(['JAN','FEB','Mar','APR'], axis=1, inplace=True)

In [275]:
psf.sort_values(['student_id'])

      student_id  MOY_PSF  EOY_PSF  spm_psf
127       st0001     17.0     56.0     11.0
4         st0002     56.0     61.0     67.0
121       st0003      4.0     66.0     20.0
9         st0004     62.0     63.0     71.0
13        st0005     51.0     60.0     67.0
135       st0006     12.0     65.0     58.0
18        st0007     17.0     69.0     14.0
22        st0008     55.0     58.0     51.0
26        st0009     19.0     19.0     15.0
30        st0010     14.0     65.0     25.0
34        st0011     29.0     60.0     70.0
38        st0012     16.0     71.0     61.0
42        st0013     48.0     60.0     71.0
46        st0014     53.0     66.0     66.0
50        st0015     17.0     65.0     52.0
139       st0016     31.0     66.0     63.0
55        st0017     44.0     55.0     71.0
60        st0019     63.0     71.0     70.0
64        st0020     17.0     56.0     21.0
68        st0021     38.0     62.0     42.0
72        st0022     36.0     60.0     44.0
76        st0023     42.0      NaN      NaN
80        st0024     48.0     61.0     55.0
84        st0025     35.0     66.0     63.0
88        st0026     56.0     58.0     65.0
92        st0027     40.0     58.0     61.0
96        st0028     16.0     61.0     34.0
100       st0029     19.0     56.0     52.0
104       st0030     49.0     71.0     65.0
108       st0031     16.0     56.0     24.0
...          ...      ...      ...      ...
12022     st1904     56.0     54.0     63.0
12026     st1905     26.0      NaN      NaN
12030     st1906      4.0      NaN      NaN
12034     st1907     30.0      NaN      NaN
12182     st1908     34.0     54.0     67.0
12186     st1909     50.0     56.0     49.0
12190     st1910     21.0     59.0     44.0
12194     st1911     48.0     56.0     70.0
12198     st1912     11.0      NaN      NaN
12202     st1913     16.0     14.0     26.0
12206     st1914     16.0     70.0     54.0
12210     st1915      9.0     61.0     40.0
12214     st1916      4.0     53.0     19.0
12218     st1917     11.0     57.0     16.0
12222     st1918     41.0     56.0     66.0
12226     st1919     15.0     62.0     42.0
12230     st1920     18.0     44.0     41.0
12234     st1921     70.0     60.0     70.0
12238     st1922      6.0     24.0     27.0
12242     st1923     13.0     55.0     55.0
12246     st1924     57.0     39.0     61.0
12250     st1925     48.0     57.0     75.0
12254     st1926     21.0     47.0     54.0
12258     st1927      1.0      3.0      0.0
12262     st1928      0.0      NaN      NaN
12266     st1929     39.0     46.0     56.0
12270     st1930     42.0     60.0     66.0
12274     st1931     10.0     53.0     61.0
12278     st1932     11.0      5.0      NaN
12427     st1933      NaN      NaN      3.0

[1359 rows x 4 columns]

In [336]:
widefy18k=pd.merge(fsf,nwf, on=['student_id'], how='outer', indicator=True)

In [337]:
widefy18k.groupby('_merge')['student_id'].nunique()

_merge
left_only      225
right_only       9
both          1218
Name: student_id, dtype: int64

In [338]:
widefy18k[widefy18k['_merge']=='right_only']

     student_id  BOY  MOY_FSF  fpm_fsf  MOY_NWF  EOY_NWF  spm_nwf      _merge
1443     st0062  NaN      NaN      NaN      NaN     22.0      NaN  right_only
1444     st0485  NaN      NaN      NaN      NaN     60.0     32.0  right_only
1445     st0576  NaN      NaN      NaN      NaN     48.0      NaN  right_only
1446     st0578  NaN      NaN      NaN      NaN     36.0     11.0  right_only
1447     st0608  NaN      NaN      NaN      NaN     53.0      NaN  right_only
1448     st0755  NaN      NaN      NaN      NaN     33.0      NaN  right_only
1449     st1195  NaN      NaN      NaN      NaN     25.0      4.0  right_only
1450     st1502  NaN      NaN      NaN      NaN     38.0      NaN  right_only
1451     st1524  NaN      NaN      NaN      NaN     46.0      NaN  right_only

In [339]:
widefy18k.rename({'_merge':'FSF_NWF'}, axis='columns', inplace=True)

In [341]:
widefy18k['FSF_NWF']=np.where(widefy18k['FSF_NWF']=='left_only','FSF no NWF',widefy18k['FSF_NWF'])
widefy18k['FSF_NWF']=np.where(widefy18k['FSF_NWF']=='right_only','NWF no FSF',widefy18k['FSF_NWF'])
widefy18k['FSF_NWF']=np.where(widefy18k['FSF_NWF']=='both','FSF & NWF',widefy18k['FSF_NWF'])

In [344]:
widefy18k.groupby(['FSF_NWF'])['student_id'].nunique()

FSF_NWF
FSF & NWF     1218
FSF no NWF     225
NWF no FSF       9
Name: student_id, dtype: int64

In [345]:
widefy18k=pd.merge(widefy18k,psf, on=['student_id'], how='outer', indicator=True)

In [346]:
widefy18k.groupby('_merge')['student_id'].nunique()

_merge
left_only       96
right_only       3
both          1356
Name: student_id, dtype: int64

In [349]:
widefy18k.rename({'_merge':'FSF_PSF'}, axis='columns', inplace=True)

In [350]:
widefy18k['FSF_PSF']=np.where(widefy18k['FSF_PSF']=='left_only','FSF no PSF',widefy18k['FSF_PSF'])
widefy18k['FSF_PSF']=np.where(widefy18k['FSF_PSF']=='right_only','PSF no FSF',widefy18k['FSF_PSF'])
widefy18k['FSF_PSF']=np.where(widefy18k['FSF_PSF']=='both','FSF & PSF',widefy18k['FSF_PSF'])

In [354]:
widefy18k=pd.merge(widefy18k,fy18eid, on=['student_id'], how='left', indicator=True)

In [356]:
widefy18k.groupby('_merge')['student_id'].nunique()

_merge
left_only        0
right_only       0
both          1455
Name: student_id, dtype: int64